#!/bin/csh -f


# This script runs the scripts that install
# software packages


./go_clhep
./go_xercesc
./go_qt
./go_geant4
./go_sconsscript
./go_evio
./go_mysql
./go_ccdb
./go_mlibrary
./go_gemc
./go_fields
./go_root
./go_banks
./go_jana

