#!/bin/csh -f


# Additional settings at the top of get_coptions
source get_coptions

# Options
set name     = evio
set release  = `./get_coptions release`
set repo     = `./get_coptions repo`/evio
set version  = $EVIO_VERSION
set filename = evio-$EVIO_VERSION".tar.gz"
set arch     = `./get_coptions arch`
set opt      = `./get_coptions copt`
./get_coptions log $name $version $filename $release $arch $opt


# Checking if the OS is 32 bit. 
set oarch = ""
if($arch == "32") then
	set oarch = 'ARCHI=x86'
endif
echo " > Special Compilation Options: " $oarch 
echo


if($1 == "src"|| $1 == "make") goto $1

# Source Build
src:

	# Getting source file
	echo " > Installing evio version "$version" - release "$release". Getting and unpacking" $filename"..."
	mkdir -p $EVIO
	cd $EVIO/..
	rm -rf   $EVIO
	rm -f      $filename
	wget $repo/$filename
	tar -zxpvf $filename > /dev/null
if($1 == "src") exit

# make
make:
	# Configuring and Compiling
	# Compiling
	echo " > Compiling evio source (log will be in "\$EVIO/"make_log)..."
	cd $EVIO

	scons $opt $oarch > make_log
if($1 == "make") exit

# Done!
echo done
echo


