#!/bin/csh -f

# Additional settings at the top of get_coptions
source get_coptions env

# Options, Screen Log, Warnings
set name     = gemc
set release  = `./get_coptions release`
set repo     = `./get_coptions repo`/gemc
set version  = $GEMC_VERSION
set filename =  gemc"-"$GEMC_VERSION".tar.gz"
set arch     = `./get_coptions arch`
set opt      = `./get_coptions copt`
./get_coptions log $name $version $filename $release $arch $opt 

# Checking if the OS is 32 bit. 
set oarch = ""
if($arch == "32") then
	set oarch = 'ARCHI=x86'
endif
set ooarch = $oarch" OPT=1"
echo " > Special Compilation Options: " $ooarch 
echo


# Build
# Getting source file
echo " > Installing gemc - release "$release". Getting source package from repository..."
rm -rf   $JLAB_SOFTWARE/gemc/$GEMC_VERSION
mkdir -p $JLAB_SOFTWARE/gemc
cd       $JLAB_SOFTWARE/gemc

rm         $filename
wget $repo/$filename
tar -zxpvf $filename > /dev/null


# Compiling
# different structure for gemc < 2
if($GEMC_VERSION == "1.8") then
	cd $JLAB_SOFTWARE/gemc/$GEMC_VERSION
	echo " > Compiling gemc source (log will be in "\$JLAB_SOFTWARE/"gemc/$GEMC_VERSION/build_log )..."
else
	cd $JLAB_SOFTWARE/gemc/$GEMC_VERSION/source
	echo " > Compiling gemc source (log will be in "\$JLAB_SOFTWARE/"gemc/$GEMC_VERSION/source/build_log )..."
endif

scons $opt $ooarch  LIBRARY="shared" > build_log

# Done!
echo done
echo


