#!/bin/csh -f

# Additional settings at the top of get_coptions
source get_coptions env

# Options, Screen Log, Warnings
set name     = mlibrary
set release  = `./get_coptions release`
set repo     = `./get_coptions repo`/mlibrary
set version  = $MLIBRARY_VERSION
set filename =  mlibrary"-"$MLIBRARY_VERSION".tar.gz"
set arch     = `./get_coptions arch`
set opt      = `./get_coptions copt`
./get_coptions log $name $version $filename $release $arch $opt 

# Checking if the OS is 32 bit. 
set oarch = ""
if($arch == "32") then
	set oarch = 'ARCHI=x86'
endif
set ooarch = $oarch" OPT=1"
echo " > Special Compilation Options: " $ooarch 
echo


# Build
# Getting source file
echo " > Installing mlibrary - release "$release". Getting source package from repository..."
rm -rf   $JLAB_SOFTWARE/mlibrary/$MLIBRARY_VERSION
mkdir -p $JLAB_SOFTWARE/mlibrary
cd       $JLAB_SOFTWARE/mlibrary

rm             $filename
wget     $repo/$filename
echo Unpacking $filename
tar -zxpvf     $filename >& /dev/null

# Compiling

cd $JLAB_SOFTWARE/mlibrary/$MLIBRARY_VERSION

echo " > Compiling mlibrary  (log will be in "\$MLIBRARY"/build_log )..."

scons $opt $ooarch > $MLIBRARY/build_log


# CADMESH is part of the mlibrary distribution
mkdir cadmeshBuild
cd cadmeshBuild
# check with geant4 p03 we still need to set CLHEP_DIR
setenv CLHEP_DIR $CLHEP_BASE_DIR
cmake ../cadmesh -DCMAKE_INSTALL_PREFIX:PATH=$JLAB_SOFTWARE/mlibrary/$MLIBRARY_VERSION
make $opt install


# Done!
echo done
echo


