#!/bin/csh -f

# Additional settings at the top of get_coptions
source get_coptions env

# Options
set name     = scons_bm
set release  = `./get_coptions release`
set repo     = `./get_coptions repo`/scons_bm
set version  = $SCONS_BM_VERSION
set filename =  scons_bm"-"$SCONS_BM_VERSION".tar.gz"


echo
echo " > Scons Build Model Version " $SCONS_BM_VERSION
echo

# Getting source file
echo " > Installing scons build model - version "$version". Getting package from repository..."
rm -rf   $JLAB_ROOT/$JLAB_VERSION/scons_bm/$SCONS_BM_VERSION
mkdir -p $JLAB_ROOT/$JLAB_VERSION/scons_bm/
cd       $JLAB_ROOT/$JLAB_VERSION/scons_bm/

rm -f       $filename
wget  $repo/$filename
tar -zxpvf  $filename > /dev/null

echo "Done."
echo

