#!/bin/tcsh -f

# This script will delete the current version of ceInstall
# and re-download them

echo
echo Deleting scripts for version $JLAB_VERSION

rm -f ceInstall_$JLAB_VERSION.tar.gz
rm -rf ce install sbsInstall

echo Re-installing scripts for version $JLAB_VERSION

wget -q http://www.jlab.org/12gev_phys/packages/sources/ceInstall/ceInstall_$JLAB_VERSION.tar.gz
mkdir ceInstall
tar -zxpf ceInstall_$JLAB_VERSION.tar.gz --strip-components 1 -C ceInstall
mv ceInstall/* .

echo Cleaning up
rm -rf ceInstall*

echo Done
echo
