#!/bin/tcsh -f

# First argument is package name
# Second argument is version

if($#argv != 2 && $1 != doc) then
	echo " "
	echo "Usage:   "
	echo  "  >> go_tar package version"
	echo " "
	exit 0
endif


set pname   = $1
set pver    = $2
set remoted = "ftp.jlab.org:/u/group/12gev_phys/www/packages/sources"
set locald  = /opt/projects

echo
echo " Package: " $pname ", version: " $pver
echo


# common environment
if($pname == "ceInstall") then
	rm -rf   $locald/ceInstall/tmp
	mkdir -p $locald/ceInstall/tmp/
	cd       $locald/ceInstall/tmp/

	wget https://github.com/JeffersonLab/ceInstall/archive/v$pver".tar.gz" -O ceInstall_$pver.tar.gz
	scp ceInstall_$pver.tar.gz $remoted/ceInstall
	cd ..
	rm -rf tmp

	# html instructions: these are the ones in the local dir, not coming from the git release
	scp sbsInstall/* $remoted/ceInstall/

	# main scripts: these are the ones in the local dir, not coming from the git release
	scp softenv.* ftp.jlab.org:/site/12gev_phys

	exit
endif


# scons scripts
if($pname == "bm") then
	rm -rf   $locald/scons_bm/tmp
	mkdir -p $locald/scons_bm/tmp/
	cd       $locald/scons_bm/tmp/

	wget https://github.com/maureeungaro/scons_bm/archive/v$pver".tar.gz" -O scons_bm_$pver.tar.gz
	scp scons_bm_$pver.tar.gz $remoted/scons_bm
	cd ..
	rm -rf tmp
	exit
endif


# Additional settings at the top of get_coptions
# Get evio from here:
# https://coda.jlab.org/drupal/content/event-io-evio
# then replace the SConstruct there with the old $EVIO/SConstruct and re-pack with (one dir up)
if($pname == "evio") then
	cd $JLAB_SOFTWARE/evio/$pver
	scons -c ; rm -rf lib bin
	cd ..
	rm -rf evio-$pver.*
	tar cvf  evio-$pver.tar --exclude="doc" --exclude="java" --exclude="tar" $pver/*
	gzip evio-$pver.tar
	scp evio-$pver.tar.gz $remoted/evio
	exit
endif

# gemc
# copying API in gemc
if($pname == "gemc") then
	if($pver == "devel") then
		cd $GEMC
		scons -c
		cd $locald/gemc/releases/
		rm -rf devel ; cp -r ../source devel
	endif
	cd $locald/gemc/releases/$pver
	scons -c ;
	cp -r $locald/gemc/api .
	cd $locald/gemc/releases
	rm -rf gemc-$pver.*
	tar cvf gemc-$pver.tar  --exclude=".DS_Store"  --exclude=".gitignore" --exclude=".sconsign.dblite" --exclude=".git" --exclude=".entitlements" --exclude="lib" $pver
	gzip gemc-$pver.tar
	scp gemc-$pver.tar.gz $remoted/gemc
	rm -rf $locald/gemc/releases/$pver/api
	exit
endif

# banks
if($pname == "banks") then
	rm -rf   $locald/banks/tmp
	mkdir -p $locald/banks/tmp/
	cd       $locald/banks/tmp/

	wget https://github.com/maureeungaro/banks/archive/v$pver".tar.gz" -O banks-$pver.tar.gz
	scp banks-$pver.tar.gz $remoted/banks
	cd ..
	rm -rf tmp
	exit
endif


# mlibrary
if($pname == "mlibrary") then
	rm -rf $locald/mlibrary/releases
	mkdir -p $locald/mlibrary/releases/$pver
	if($pver == "devel") then
		cd $locald/mlibrary/
		scons -c
		./installCmesh   # make sure the cadmesh included match the release version
		rm -rf cadmeshBuild lib include
		set toCopy = `\ls | grep -v releases | grep -v doxygenREADME`
		cp -r $toCopy releases/devel/
	else
		# the numbered releases of the mlibraries are done with github
		# get them here:
		# https://github.com/gemc/mlibrary/releases
		# remember to run ./installCmesh and make the release
		# then make the release by hand at https://github.com/gemc/mlibrary/releases
		cd $locald/mlibrary/releases/
		wget https://github.com/gemc/mlibrary/archive/v$pver".tar.gz"
		tar -zxpf v$pver.tar.gz
		mv mlibrary-$pver $pver
	endif

	cd $locald/mlibrary/releases/
	rm -rf mlibrary-$pver.*

	tar cvf mlibrary-$pver.tar --exclude=".DS_Store"  --exclude=".gitignore" --exclude=".sconsign.dblite" --exclude=".git" --exclude=".entitlements" $pver/*
	gzip mlibrary-$pver.tar
	scp mlibrary-$pver.tar.gz $remoted/mlibrary

	rm mlibrary-$pver.tar.gz
	exit
endif




echo
echo


