#!/bin/zsh

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

filename="mlibrary/mlibrary_$MLIBRARY_VERSION.tar.gz" # includes subdirectory name
tar_strip=1                                           # in the tarball, the source is inside mlibrary-version

# tar packages downloaded on the farm with:
# cd /group/12gev_phys/www/packages/sources/mlibrary
# wget https://github.com/gemc/mlibrary/archive/refs/tags/v1.7.tar.gz -O mlibrary-1.7.tar.gz


base_dir=$MLIBRARY


log_general mlibrary "$MLIBRARY_VERSION" "$filename" "$base_dir"

unpack_source_in_directory "$filename" "$base_dir" "$tar_strip"

# notice that if the system is updated, the OPENGL library may point to a different location
# for example /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/OpenGL.framework instead of 13.0
cd $MLIBRARY
./compileCmesh 2>"cmesh_build_err.txt" 1>"cmesh_build_log.txt" || exit

scons_build_and_install "$base_dir"

