#!/bin/zsh -i

. "$(dirname "$(readlink -f "$0")")"/functions.zsh


# parse argument. If no argument given, set version to all available physlibs modules
if [[ $# -eq 0 ]]; then
	physlibs_version=$( ls $(dirname "$(readlink -f "$0")")"/../modules/modulefiles/physlibs/" )
else
	physlibs_version=$1
fi


echo " > phys_version(s): $=physlibs_version"
echo

for pv in  $=physlibs_version ; do

	echo " > Checking missing modules in physlibs version $pv"
	module unload physlibs     -s
	module load	  physlibs/$pv -s

	[ "$(moduleTestResult .clhep     $CLHEP_VERSION )"    -eq 0 ] && echo " > clhep is installed"    || install_clhep
	[ "$(moduleTestResult .xercesc   $XERCESC_VERSION )"  -eq 0 ] && echo " > xercesc is installed"  || install_xercesc
  [ "$(moduleTestResult .qt        $QT_VERSION)"        -eq 0 ] && echo " > qt is installed"       || copy_qt
	[ "$(moduleTestResult .g4data    $G4_VERSION)"        -eq 0 ] && echo " > g4data is installed"   || install_geant4_data
	[ "$(moduleTestResult .geant4    $G4_VERSION)"        -eq 0 ] && echo " > geant4 is installed"   || install_geant4

done
echo
