#!/bin/zsh -i

# -i: interactive mode. Needed to load modules

. "$(dirname "$(readlink -f "$0")")"/functions.zsh

# parse argument. If no argument given, set version to all available sim modules
if [[ $# -eq 1 ]]; then
	sim_version=$1
else
	# error
	echo " > ERROR: No sim version given. Exiting."
	exit 1
fi


echo " > sim_version: $sim_version"
echo


echo " > Checking missing modules in sim version $sim_version"
module unload sim/$sim_version -s
module load	  sim/$sim_version -s

[ "$(moduleTestResult .clhep     $CLHEP_VERSION )"    -eq 0 ] && echo " > clhep is installed"    || install_clhep
[ "$(moduleTestResult .xercesc   $XERCESC_VERSION )"  -eq 0 ] && echo " > xercesc is installed"  || install_xercesc
[ "$(moduleTestResult .qt        $QT_VERSION)"        -eq 0 ] && echo " > qt is installed"       || copy_qt
[ "$(moduleTestResult .g4data    $G4_VERSION)"        -eq 0 ] && echo " > g4data is installed"   || install_geant4_data
[ "$(moduleTestResult .geant4    $G4_VERSION)"        -eq 0 ] && echo " > geant4 is installed"   || install_geant4

echo
