#!/bin/zsh

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

filename="hipo/hipo-$HIPO_VERSION.tar.gz" # includes subdirectory name
tar_strip=1                               # in the tarball, the source is inside version


base_dir=$HIPO

log_general hipo "$HIPO_VERSION" "$filename" "$base_dir"

unpack_source_in_directory "$filename" "$base_dir" "$tar_strip"


# the tar file must contain the lz4 submodule. Done with:
# git clone --recurse-submodules https://github.com:gavalian/hipo.git
# tar cvf hipo-1.8.tar hipo ;  gzip hipo-1.8.tar

cd $HIPO
cd lz4
make -j "$n_cpu"
cp lib/liblz4.* ../lib
cd ../
cmake .
cd hipo4
make -j "$n_cpu"




