#!/bin/zsh

source "$(dirname "$(readlink -f "$0")")"/functions

filename="geant4/geant4-v$GEANT4_VERSION.tar.gz" # includes subdirectory name
tar_strip=1                               # in the tarball, the source is inside VERSION/CLHEP

# tarball name is different in old geant4 version
if [[ $PHYS_VERSION == 2.4* || $PHYS_VERSION == 2.5* ]]; then
    filename="geant4/geant$GEANT4_VERSION.tar.gz"
    tar_strip=1
fi


source_dir=$CLHEP_BASE_DIR/../source
build_dir=$CLHEP_BASE_DIR/../build
base_dir=$CLHEP_BASE_DIR
cmake_options="-Wno-dev"




source_dir=$CLHEP_BASE_DIR/../source
build_dir=$CLHEP_BASE_DIR/../build
base_dir=$CLHEP_BASE_DIR
cmake_options="-Wno-dev"


log_general clhep "$CLHEP_VERSION" "$filename" "$base_dir"

#unpack_source_in_directory "$filename" "$source_dir" "$tar_strip"

#cmake_build_and_install "$source_dir" "$build_dir" "$cmake_options" "$base_dir"

