#!/bin/zsh -i

function testResult() {
	library=$1
	version=$2

	module test $library/$version
	echo $?
}


# parse argument. If no argument given, set version to all available physlibs modules
if [[ $# -eq 0 ]]; then
	physlibs_version=$( ls $(dirname "$(readlink -f "$0")")"/../modules/modulefiles/physlibs/" )
else
	physlibs_version=$1
fi


echo " > phys_version(s): $=physlibs_version"
echo

for pv in  $=physlibs_version ; do

	echo " > Checking missing modules in physlibs version $pv"
	module unload physlibs     -s
	module load	  physlibs/$pv -s

	[[ $(testResult .clhep     $CLHEP_VERSION)    == "0" ]] && echo " > clhep is installed"    || install_clhep
	[[ $(testResult .xercesc   $XERCESC_VERSION)  == "0" ]] && echo " > xercesc is installed"  || install_xercesc
	[[ $(testResult .qt        $QT_VERSION)       == "0" ]] && echo " > qt is installed"       || copy_qt
	[[ $(testResult .g4data    $G4_VERSION)       == "0" ]] && echo " > g4data is installed"   || install_geant4_data
	[[ $(testResult .geant4    $G4_VERSION)       == "0" ]] && echo " > geant4 is installed"   || install_geant4
	[[ $(testResult .scons_bm  $SCONS_BM_VERSION) == "0" ]] && echo " > scons_bm is installed" || install_scons_bm
	[[ $(testResult .ccdb      $CCDB_VERSION)     == "0" ]] && echo " > ccdb is installed"     || install_ccdb
	[[ $(testResult .evio      $EVIO_VERSION)     == "0" ]] && echo " > evio is installed"     || install_evio
	[[ $(testResult .mlibrary  $MLIBRARY_VERSION) == "0" ]] && echo " > mlibrary is installed" || install_mlibrary
	[[ $(testResult .hipo      $HIPO_VERSION)     == "0" ]] && echo " > hipo is installed"     || install_hipo
	[[ $(testResult .cmag      $CMAG_VERSION)     == "0" ]] && echo " > cmag is installed"     || install_cmag

	for c12tag in $=CLAS12TAGS; do
	 	echo " > Testing $c12tag"
	 	# notice module switch does not work
	 	# module switch "clas12Tags/$c12tag" -s
		[[ $(testResult clas12Tags $c12tag) == "PASS" ]] && echo " > clas12Tags  $c12tag is installed" || install_clas12Tags $c12tag
	done

	echo
	module test physlibs/$pv

done
echo
