#!/bin/zsh -i

function testResult() {
	library=$1
	version=$2

	mtest=$(module test $library/$version | grep result | awk '{print $3}')

	echo $mtest
}


# parse argument. If no argument given, set version to all available physlibs modules
if [[ $# -eq 0 ]]; then
	physlibs_version=$( ls $(dirname "$(readlink -f "$0")")"/../modules/modulefiles/physlibs/" )
else
	physlibs_version=$1
fi


echo " > Installing phys_version(s): $=physlibs_version"
echo

for pv in  $=physlibs_version ; do

	echo " > Checking missing modules in physlibs version $pv"
	module unload physlibs     -s
	module load	  physlibs/$pv -s

	[[ $(testResult .clhep     $CLHEP_VERSION)    == "PASS" ]] && echo " > clhep is installed"    || install_clhep
	[[ $(testResult .xercesc   $XERCESC_VERSION)  == "PASS" ]] && echo " > xercesc is installed"  || install_xercesc
	[[ $(testResult .qt        $QT_VERSION)       == "PASS" ]] && echo " > qt is installed"       || copy_qt
	[[ $(testResult .g4data    $G4_VERSION)       == "PASS" ]] && echo " > g4data is installed"   || install_geant4_data
	[[ $(testResult .geant4    $G4_VERSION)       == "PASS" ]] && echo " > geant4 is installed"   || install_geant4

done
echo
