#!/bin/zsh


source "$(dirname "$(readlink -f "$0")")"/functions.zsh

filename="gemc3/gemc3-$GEMC3_VERSION.tar.gz" # includes subdirectory name
tar_strip=1                                  # in the tarball, the source is inside version




base_dir=$GEMC3

log_general clas12Tags "$C12TAG_VERSION" "$filename" "$base_dir"

unpack_source_in_directory "$filename" "$base_dir" "$tar_strip"

scons_build_and_install "$base_dir/source"

