#!/bin/zsh

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

filename="scig/scig-$SCIG_VERSION.tar.gz" # includes subdirectory name
tar_strip=1                                           # in the tarball, the source is inside scons_bm

base_dir="$SCIG"


log_general scig "$SCIG_VERSION" "$filename" "$base_dir"

unpack_source_in_directory "$filename" "$base_dir" "$tar_strip"

echo "$magenta > scig installation completed.$reset"
echo

