#!/bin/zsh

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

filename="gemc/gemc3-$GEMC3_VERSION.tar.gz" # includes subdirectory name
tar_strip=1                                  # in the tarball, the source is inside version

# tar packages downloaded on the farm with:
# cd /group/12gev_phys/www/packages/sources/gemc
# wget https://github.com/gemc/src/archive/refs/tags/1.0.tar.gz -O gemc3-1.0.tar.gz

base_dir=$GEMC3_BASE_DIR/$GEMC3_VERSION

log_general gemc3 "$GEMC3_VERSION" "$filename" "$base_dir"

unpack_source_in_directory "$filename" "$base_dir" "$tar_strip"

scons_build_and_install "$base_dir"

