#!/bin/csh -f

# Get the jana tar file from the jana website:
# http://www.jlab.org/JANA/downloads.php
# zip if necessary, and copy to:
# ftp:/u/group/12gev_phys/www/packages/sources/jana

# Additional settings at the top of get_coptions
source get_coptions env

# Options, Screen Log, Warnings
set name     = jana
set release  = `./get_coptions release`
set repo     = `./get_coptions repo`/jana
set version  = $JANA_VERSION
set filename =  jana"_"$JANA_VERSION".tgz"
set arch     = `./get_coptions arch`
set opt      = `./get_coptions copt`
./get_coptions log $name $version $filename $release $arch $opt



# Build
# Getting source file
echo " > Installing jana - release "$release". Getting package source from repository..."
rm -rf   $JLAB_SOFTWARE/jana/$JANA_VERSION
mkdir -p $JLAB_SOFTWARE/jana/$JANA_VERSION
cd       $JLAB_SOFTWARE/jana

rm -f      $filename
wget $repo/$filename
tar -zxpvf $filename > /dev/null


# Compiling
echo " > Compiling jana source (log will be in "\$JLAB_SOFTWARE/"jana/jana_$JANA_VERSION/build_log )..."
cd $JLAB_SOFTWARE/jana/jana"_"$JANA_VERSION

setenv BMS_OSNAME $OSRELEASE

scons $opt install >& build_log

mv $BMS_OSNAME/* $JLAB_SOFTWARE/jana/$JANA_VERSION


# Removing tar file
rm -rf $JLAB_SOFTWARE/jana/$filename
rm -rf $JLAB_SOFTWARE/jana/jana_$JANA_VERSION


# Done!
echo done
echo


