#!/bin/csh -f


# Options, Screen Log, Warnings
set release  = `./get_coptions release`
set name     = `echo $0 | awk -F\_ '{print $2}'`
set version  = `./get_coptions version  $name`
set filename = `./get_coptions filename $name`
set arch     = `./get_coptions arch`
set opt      = `./get_coptions copt`
./get_coptions log $name $version $filename $release $arch $opt 

# Checking if the OS is 32 bit. 
set oarch = ""
if($arch == "32") then
	set oarch = 'ARCHI=x86'
endif
set ooarch = $oarch" OPT=1"
echo " > Special Compilation Options: " $ooarch 
echo


#######
# Build
#######
# Getting source file
echo " > Installing scrat - release "$release". Getting source from repository..."
mkdir -p $SCRAT
cd $JLAB_SOFTWARE
svn co https://clas12svn.jlab.org/repos/clas12/scrat/trunk scrat

# Compiling
echo " > Compiling scrat source (log will be in "\$SCRAT/"make_log)..."
cd $SCRAT

scons $opt $ooarch > make_log

# Done!
echo done
echo


