#!/bin/csh -f




# Options, Screen Log, Warnings
set name     = gemc_evio2root
set release  = `./get_coptions release`
set repo     = `./get_coptions repo`/gemc_evio2root
set version  = latest
set filename = gemc_evio2root".tar.gz"
set arch     = `./get_coptions arch`
set opt      = `./get_coptions copt`
./get_coptions log $name $version $filename $release $arch $opt

# Checking if the OS is 32 bit.
set oarch = ""
if($arch == "32") then
set oarch = 'ARCHI=x86'
endif
set ooarch = $oarch" OPT=1"
echo " > Special Compilation Options: " $ooarch
echo


# Build
# Getting source file
echo " > Installing gemc_evio2root - release "$release". Getting source package from repository..."
rm -rf   $JLAB_SOFTWARE/gemc_evio2root
mkdir -p $JLAB_SOFTWARE/gemc_evio2root
cd       $JLAB_SOFTWARE/gemc_evio2root

rm         $filename
wget $repo/$filename
tar -zxpvf $filename > /dev/null


# Compiling
cd $JLAB_SOFTWARE/gemc_evio2root
echo " > Compiling banks source (log will be in "\$JLAB_SOFTWARE/"gemc_evio2root/build_log )..."


scons $opt $ooarch > build_log

# Done!
echo done
echo

