#!/bin/zsh

magenta=`tput setaf 5`
reset=`tput sgr0`

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

# Assumes that qt5 is install with:
# Darwin: brew install qt5
# Linux:  yum install qt5-qtbase-devel

# The files are copied to $QTDIR instead of linked for reuse in container/cvmfs
# and avoid ambiguity with other system libraries

dir_remove_and_create "$QTDIR"

# load module for the current OS
# to find the includes (after the path to qmake is set)
# qmake -query QT_INSTALL_HEADERS
# linux other paths:
# qtchooser -print-env
case $(uname -s) in
    Darwin)
        brewDir="$(brew --prefix)/Cellar/qt@5"
		    minorQtVersion=$(\ls -rt "$brewDir" | tail -1)
		    SQTDIR="$brewDir/$minorQtVersion"

        echo
        echo " > Using brew-installed System QT, version $minorQtVersion"
		    echo " > Origin: $brewDir"
		    echo " > Destination: $QTDIR"
		    echo

		    cp -r "$SQTDIR/lib"     "$QTDIR"
		    cp -r "$SQTDIR/include" "$QTDIR"
		    cp -r "$SQTDIR/bin"     "$QTDIR"
		    cp -r "$SQTDIR/mkspecs" "$QTDIR"
		    cp -r "$SQTDIR/plugins" "$QTDIR"

        echo "$magenta > QT Libraries / Includes copy completed.$reset"
        echo " Content of $QTDIR:"
  	    ls -l "$QTDIR"

        ;;

    Linux)
        # fedora line
        if [ -f /etc/fedora-release ] || [ -f /etc/redhat-release ]; then
            echo  " > QT Line: Fedora/Redhat/CentOS"
            SQTDIR=/usr/lib64            # libraries like libQt5Xml.so
            QTDIR_INCS=/usr/include/qt5  # includes
            SQTDIR_ALL=$SQTDIR/qt5       # binaries, mkspecs and plugins

        # ubuntu line
        elif [ -f /etc/os-release ]; then
            echo  " > QT Line: Ubuntu "
            SQTDIR=/usr/lib/x86_64-linux-gnu
            QTDIR_INCS=/usr/include/x86_64-linux-gnu/qt5  # includes
            SQTDIR_ALL=$SQTDIR/qt5       # binaries, mkspecs and plugins
        else
            echo  " > Linux line not supported yet "
        fi

        dir_remove_and_create "$QTDIR/lib"
        cp       "$SQTDIR"/libQt*      "$QTDIR/lib"
        cp -r -L "$QTDIR_INCS"         "$QTDIR"
        cp -r -L "$SQTDIR_ALL/bin"     "$QTDIR"
        cp -r -L "$SQTDIR_ALL/mkspecs" "$QTDIR"
        cp -r -L "$SQTDIR_ALL/plugins" "$QTDIR"

        echo "$magenta > QT Libraries / Includes copy completed.$reset"
        echo " Content of $QTDIR:"
  	    ls -l "$QTDIR"
       ;;

    *)
        echo "$magenta > Unsupported OS: $(uname -s) $reset"
        exit 1
        ;;
esac



