#!/bin/csh -f

# Additional settings at the top of get_coptions
source get_coptions env
set getCoptions = $JLAB_ROOT/$JLAB_VERSION/install/get_coptions 

# Options, Screen Log, Warnings
set name     = banks
set release  = `./get_coptions release`
set repo     = `./get_coptions repo`/banks
set version  = $BANKS_VERSION
set filename = banks_$BANKS_VERSION".tar.gz"
set arch     = `./get_coptions arch`
set opt      = `./get_coptions copt`
./get_coptions log $name $version $filename $release $arch $opt 

# Checking if the OS is 32 bit. 
set oarch = ""
if($arch == "32") then
	set oarch = 'ARCHI=x86'
endif
set ooarch = $oarch" OPT=1"
echo " > Special Compilation Options: " $ooarch 
echo


# Build
# Getting source file
echo " > Installing banks - release "$release". Getting source package from repository..."
rm -rf   $JLAB_SOFTWARE/banks/$BANKS_VERSION
mkdir -p $JLAB_SOFTWARE/banks/$BANKS_VERSION
cd       $JLAB_SOFTWARE/banks

rm             $filename
wget -q  $repo/$filename
echo Unpacking $filename
tar -zxpf      $filename --strip-components 1 -C $BANKS_VERSION


# Compiling
cd $JLAB_SOFTWARE/banks/$BANKS_VERSION
echo " > Compiling banks source (log will be in "\$JLAB_SOFTWARE/"banks/$BANKS_VERSION/build_log )..."


scons $opt $ooarch > build_log

# Done!
echo done
echo
