#!/bin/csh -f

# Additional settings at the top of get_coptions
source get_coptions env
set getCoptions = $JLAB_ROOT/$JLAB_VERSION/install/get_coptions 

# Options, Screen Log, Warnings
set name     = banks
set release  = `$getCoptions release`
set repo     = `$getCoptions repo`/banks
set version  = $BANKS_VERSION
set filename = banks_$BANKS_VERSION".tar.gz"
set arch     = `$getCoptions arch`
set opt      = `$getCoptions copt`
set blog     = `$getCoptions logFile banks`
set blogS    = `$getCoptions logFileS banks`

# Write options on screen
$getCoptions log $name $version $filename $release $arch $opt

if($1 == "src"|| $1 == "make") goto $1

# Source Build
src:
	# start message
	$getCoptions installLog $name $version

	# creating build and source dirs
	$getCoptions removeAndCreate $JLAB_SOFTWARE/banks/$BANKS_VERSION

	# unpacking inside source
	cd $JLAB_SOFTWARE/banks
	$getCoptions getAndUnpackTo $repo $filename $BANKS_VERSION
if($1 == "src") exit

# make
make:

	# log start of compilation
	$getCoptions logStart $blog $blogS

	cd $JLAB_SOFTWARE/banks/$BANKS_VERSION

	scons $opt OPT=1 >> $blog

	# log end of compilation, total time
	$getCoptions logEnd  $blog
	$getCoptions logTime $blog

if($1 == "make") exit

# Done
echo " > Done."
echo



