#!/bin/csh -f

# Get the ccdb tar file from the ccdb website:
# https://halldweb1.jlab.org/wiki/index.php/Calibration_Database
# and copy to:
# ftp:/u/group/12gev_phys/www/packages/sources/ccdb

# Additional settings at the top of get_coptions
source get_coptions env
set getCoptions = $JLAB_ROOT/$JLAB_VERSION/install/get_coptions 

# Options, Screen Log, Warnings
set name     = ccdb
set release  = `./get_coptions release`
set repo     = `./get_coptions repo`/ccdb
set version  = $CCDB_VERSION
set filename =  ccdb"-"$CCDB_VERSION".tar.gz"
set arch     = `./get_coptions arch`
set opt      = `./get_coptions copt`
set blog     = `./get_coptions logFile ccdb`
set blogS    = `./get_coptions logFileS ccdb`

# Write options on screen
./get_coptions log $name $version $filename $release $arch $opt

if($1 == "src"|| $1 == "make") goto $1

# Source Build
src:
	# start message
	$getCoptions installLog $name $version

	# creating build and source dirs
	$getCoptions removeAndCreate $JLAB_SOFTWARE/ccdb

	# unpacking inside source
	cd $JLAB_SOFTWARE/ccdb
	$getCoptions getAndUnpack $repo $filename
if($1 == "src") exit

# make
make:

	# log start of compilation
	$getCoptions logStart $blog $blogS

	cd $JLAB_SOFTWARE/ccdb/ccdb"-"$CCDB_VERSION
	scons $opt >> $blog

	# log end of compilation, total time
	$getCoptions logEnd  $blog
	$getCoptions logTime $blog

if($1 == "make") exit

# Cleaning up
echo " > Cleaning up..."
# uncomment this if they need debugging
rm -rf $JLAB_SOFTWARE/ccdb/$filename

# Done
echo " > Done."
echo

