#!/bin/csh -f

# getCoptions points to script
set getCoptions = $JLAB_ROOT/$JLAB_VERSION/install/get_coptions 

# Options, Screen Log, Warnings
set name     = gemc
set release  = `$getCoptions release`
set repo     = `$getCoptions repo`/clas12g3
set version  = $CLAS12G3_VERSION
set filename =  clas12"-"$CLAS12G3_VERSION".tar.gz"
set opt      = `$getCoptions copt`
set blog     = `$getCoptions logFile gemc`
set blogS    = `$getCoptions logFileS gemc`

# Write options on screen
$getCoptions log $name $version $filename $release $opt

if($1 == "src"|| $1 == "make") goto $1

# Source Build
src:
	# start message
	$getCoptions installLog $name $version

	# creating build and source dirs
	$getCoptions removeAndCreate $JLAB_SOFTWARE/gemc/$GEMC_VERSION

	# unpacking 
	cd $JLAB_SOFTWARE/gemc
	$getCoptions getAndUnpackTo $repo $filename $version
if($1 == "src") exit

# make
make:


	# copying plugins to GPLUGIN_PATH
	cd sci-g/examples/plugins/calorimeter/plugin/
	scons $opt OPT=1 >>  $blog
	cp ch.gplugin $GPLUGIN_PATH


	# log start of compilation
	$getCoptions logStart $blog $blogS

	# start showing log on xterm
	$getCoptions xLog gemc

	# Adding LIBRARY="shared" in case gemc is built as a library
	cd $GEMC
	scons $opt OPT=1 LIBRARY="shared" >>  $blog

	# log end of compilation, total time
	$getCoptions logEnd  $blog
	$getCoptions logTime $blog

# Done
echo " > Done."
echo

exit





