#!/bin/csh -f


# version is hardcoded here... it doesn't change that much
set rootDir  = dawn_3_91a
set dawnFile = $rootDir".tgz"
set dawnDir = dawn

rm -rf $JLAB_SOFTWARE/$dawnDir
mkdir -p $JLAB_SOFTWARE/$dawnDir
cd $JLAB_SOFTWARE
curl -s http://geant4.kek.jp/~tanaka/src/$dawnFile -O -L
tar -zxpvf $dawnFile -C $dawnDir
cd $dawnDir
mv $rootDir/* .
rm -rf $rootDir
make -j12

# now a trick to use dawn -d
cd $JLAB_SOFTWARE/$dawnDir
mv dawn dawnd ; touch dawn
echo "/opt/jlab_software/2.6/Darwin_macosx12.5-clang13.1.6/dawn/dawnd -d "'$1' >> dawn
chmod a+x dawn

