#!/bin/csh -f


# version is hardcoded here... it doesn't change that much
set rootDir  = dawn_3_91a
set dawnFile = $rootDir".tgz"
set dawnDir = dawn

rm -rf $JLAB_SOFTWARE/$dawnDir
mkdir -p $JLAB_SOFTWARE/$dawnDir
cd $JLAB_SOFTWARE
set remoteFile=https://www.jlab.org/12gev_phys/packages/sources/dawn/$dawnFile
echo fetching $remoteFile
curl $remoteFile -O -L
tar -zxpvf $dawnFile -C $dawnDir
echo dawnDir: $dawnDir
cd $dawnDir
echo pwd:
pwd
echo content:
ls -lrt

mv $rootDir/* .
rm -rf $rootDir

set copt = " -j"`getconf _NPROCESSORS_ONLN`" OPT=1"
echo copt: $copt

make $copt

# now a trick to use dawn -d
mv dawn dawnd ; touch dawn
echo "$JLAB_SOFTWARE/$dawnDir/dawnd -d "'$1' >> dawn
chmod a+x dawn
echo
echo content after installation:
ls -lrt

