#!/bin/csh -f


# Additional settings at the top of get_coptions
# Get evio from here:
# https://coda.jlab.org/drupal/content/event-io-evio
# then replace the SConstruct there with the old $EVIO/SConstruct and re-pack with (one dir up)
# Also need to copy
# set version = 5.1
# tar cvf evio-$version.tar --exclude="doc" --exclude="java" --exclude="tar" evio-$version/*
# gzip evio-$version.tar
# scp evio-$version.tar.gz ftp:/u/group/12gev_phys/www/packages/sources/evio

source get_coptions env
set getCoptions = $JLAB_ROOT/$JLAB_VERSION/install/get_coptions 

# Options
set name     = evio
set release  = `$getCoptions release`
set repo     = `$getCoptions repo`/evio
set version  = $EVIO_VERSION
set filename = evio-$EVIO_VERSION".tar.gz"
set opt      = `$getCoptions copt`
set blog     = `$getCoptions logFile clhep`
set blogS    = `$getCoptions logFileS clhep`

# Write options on screen
$getCoptions log $name $version $filename $release $opt



if($1 == "src"|| $1 == "make") goto $1

# Source Build
src:

	# start message
	$getCoptions installLog $name $version

	$getCoptions removeAndCreate $EVIO
	cd $EVIO/..

	$getCoptions getAndUnpackTo $repo $filename $version
if($1 == "src") exit

# make
make:
	# log start of compilation
	$getCoptions logStart $blog $blogS

	cd $EVIO

	scons $opt OPT=1 >> $blog
if($1 == "make") exit

# Done!
echo done
echo


