#!/bin/csh -f

# Field location on remote disk location:
# /u/group/clas/www/clasweb/html/12gev/field_maps

# Additional settings at the top of get_coptions
set getCoptions = $JLAB_ROOT/$JLAB_VERSION/install/get_coptions 

# Linux: -c = do not get file if already done.
if (`uname` == "Linux") then
	set mwget = "wget -c -nv --no-check-certificate"
# Mac: makes it quite and show nice progress
else if (`uname` == "Darwin") then
	set mwget = "wget -qc --show-progress --no-check-certificate"
endif


# Magnetic Fields Maps Installation
echo " > Getting maps from the repository."
mkdir -p $JLAB_ROOT/noarch/data
cd       $JLAB_ROOT/noarch/data
rm -rf srr* clas12*

$mwget http://clasweb.jlab.org/12gev/field_maps/clas12NewSolenoidFieldMap.dat
$mwget http://clasweb.jlab.org/12gev/field_maps/TorusSymmetric.dat
echo " > done."
echo

# Getting the geometry - starting with gemc 2.0 the geometry is versioned internally
