#!/bin/csh -f

# Field location on remote disk location:
# /u/group/clas/www/clasweb/html/12gev/field_maps

# Additional settings at the top of get_coptions
set getCoptions = $JLAB_ROOT/$JLAB_VERSION/install/get_coptions 

# Linux: -c = do not get file if already done.
if (`uname` == "Linux") then
	set mwget = "wget -c -nv --no-check-certificate"
# Mac: makes it quite and show nice progress
else if (`uname` == "Darwin") then
	set mwget = "wget -qc --show-progress --no-check-certificate"
endif

if($1 == "txt" || $1 == "c12b"  || $1 == "clean") then
	goto $1
endif

# clean
clean:

	# Magnetic Fields Maps Installation
	echo " > Getting maps from the repository."
	mkdir -p $JLAB_ROOT/noarch/data
	cd       $JLAB_ROOT/noarch/data
	rm -rf srr* clas12*

if($1 == "clean") exit

# txt
txt:

	$mwget http://clasweb.jlab.org/12gev/field_maps/clas12NewSolenoidFieldMap.dat
	$mwget http://clasweb.jlab.org/12gev/field_maps/TorusSymmetric.dat
	$mwget http://clasweb.jlab.org/12gev/field_maps/Full_torus_r251_phi181_z251_03March2020.dat
	$mwget http://clasweb.jlab.org/12gev/field_maps/Symm_solenoid_r601_phi1_z1201_13June2018.dat
	$mwget http://clasweb.jlab.org/12gev/field_maps/Symm_torus_r2501_phi16_z251_24Apr2018.dat
	echo " > done."
	echo

if($1 == "txt") exit

# txt
c12b:

	cd $JLAB_SOFTWARE
	git clone https://github.com/JeffersonLab/clas12-cmag cmag
	cd cmag/src
	make -j4

if($1 == "c12b") exit


# Getting the geometry - starting with gemc 2.0 the geometry is versioned internally


