#!/bin/csh -f

# Field location on remote disk location:
# /u/group/clas/www/clasweb/html/12gev/field_maps

# Additional settings at the top of get_coptions
source get_coptions env
set getCoptions = $JLAB_ROOT/$JLAB_VERSION/install/get_coptions 

# Magnetic Fields Maps Installation
echo " > Getting maps from the repository."
mkdir -p $JLAB_ROOT/noarch/data
cd       $JLAB_ROOT/noarch/data
rm -rf srr* clas12*

wget -c http://clasweb.jlab.org/12gev/field_maps/clas12SolenoidFieldMap.dat
wget -c http://clasweb.jlab.org/12gev/field_maps/TorusSymmetric.dat
echo " > done."
echo

# Getting the geometry - starting with gemc 2.0 the geometry is versioned internally
