#!/bin/csh -f

# Additional settings at the top of get_coptions
set getCoptions = $JLAB_ROOT/$JLAB_VERSION/install/get_coptions 

# Options, Screen Log, Warnings
set name     = glibrary
set release  = `$getCoptions release`
set repo     = `$getCoptions repo`/glibrary
set version  = $GLIBRARY_VERSION
set filename =  glibrary"_"$GLIBRARY_VERSION".tar.gz"
set opt      = `$getCoptions copt`
set blog     = `$getCoptions logFile glibrary`
set blogS    = `$getCoptions logFileS glibrary`

# Write options on screen
$getCoptions log $name $version $filename $release $opt

if($1 == "src"|| $1 == "make") goto $1

# Source Build
src:
	# start message
	$getCoptions installLog $name $version

	# creating build and source dirs
	$getCoptions removeAndCreate $JLAB_SOFTWARE/glibrary/$GLIBRARY_VERSION

	# unpacking inside source
	cd $JLAB_SOFTWARE/glibrary
	$getCoptions getAndUnpackTo $repo $filename $GLIBRARY_VERSION
if($1 == "src") exit

# make
cadmesh:

	cd $GLIBRARY

	# log start of compilation
	$getCoptions logStart $blog $blogS

	# start showing log on xterm
	$getCoptions xLog glibrary

	# cadmesg
	./compileCmesh >>  $blog

	# Adding LIBRARY="shared" in case gemc is built as a library
	scons $opt OPT=1  >>  $blog

	# log end of compilation, total time
	$getCoptions logEnd  $blog
	$getCoptions logTime $blog

if($1 == "make") exit

# Done
echo " > Done."
echo





