#!/bin/csh -f

# Additional settings at the top of get_coptions
set getCoptions = $JLAB_ROOT/$JLAB_VERSION/install/get_coptions 

# Options, Screen Log, Warnings
set name     = glibrary
set release  = `$getCoptions release`
set repo     = `$getCoptions repo`/glibrary
set version  = $GLIBRARY_VERSION
set filename =  glibrary"_"$GLIBRARY_VERSION".tar.gz"
set opt      = `$getCoptions copt`
set blog     = `$getCoptions logFile glibrary`
set blogS    = `$getCoptions logFileS glibrary`

# Write options on screen
$getCoptions log $name $version $filename $release $opt

if($1 == "src"|| $1 == "cadmesh" || $1 == "make") goto $1

# get source code
src:

	# start message
	$getCoptions installLog $name $GLIBRARY_VERSION
	rm -rf $JLAB_SOFTWARE/glibrary/$GLIBRARY_VERSION
	mkdir $JLAB_SOFTWARE/glibrary
	cd $JLAB_SOFTWARE/glibrary
	git clone https://github.com/gemc/glibrary $GLIBRARY_VERSION

if($1 == "src") exit


# build cadmesh
cadmesh:
	cd $GLIBRARY

	# log start of compilation
	$getCoptions logStart $blog $blogS

	# start showing log on xterm
	$getCoptions xLog glibrary

	# cadmesg
	./compileCmesh >>  $blog

	# log end of compilation, total time
	$getCoptions logEnd  $blog
	$getCoptions logTime $blog

if($1 == "cadmesh") exit

# build glibrary
make:
	cd $GLIBRARY

	# log start of compilation
	$getCoptions logStart $blog $blogS

	# start showing log on xterm
	$getCoptions xLog glibrary

	# Adding LIBRARY="shared" in case gemc is built as a library
	scons $opt OPT=1  >>  $blog

if($1 == "make") exit


# Done
echo " > Done."
echo





