#!/bin/csh -f

# getCoptions points to script
set getCoptions = $JLAB_ROOT/$JLAB_VERSION/install/get_coptions 

# Options, Screen Log, Warnings
set name     = hipo
set release  = `$getCoptions release`
set repo     = `$getCoptions repo`/hipo
set version  = $HIPO_VERSION
set filename = hipo-$HIPO_VERSION".tar.gz"
set opt      = `$getCoptions copt`
set blog     = `$getCoptions logFile hipo`
set blogS    = `$getCoptions logFileS hipo`

# Write options on screen
$getCoptions log $name $version $filename $release $opt

if($1 == "src"|| $1 == "make") goto $1

# Source Build
src:
	# start message
	$getCoptions installLog $name $version

	# creating build and source dirs
	$getCoptions removeAndCreate $HIPO

	# unpacking 
	cd $HIPO/..
	$getCoptions getAndUnpackTo $repo $filename $version
if($1 == "src") exit

# make
make:
	# log start of compilation
	$getCoptions logStart $blog $blogS

	# start showing log on xterm
	$getCoptions xLog hipo

	cd $HIPO
	cmake .
	cd hipo4
	make $opt OPT=1


if($1 == "make") exit

# Done!
echo done
echo


