#!/bin/csh -f

# Get the jana tar file from the jana website:
# http://www.jlab.org/JANA/downloads.php
# zip if necessary, and copy to:
# ftp:/u/group/12gev_phys/www/packages/sources/jana

# Additional settings at the top of get_coptions
source get_coptions env
set getCoptions = $JLAB_ROOT/$JLAB_VERSION/install/get_coptions 

# Options, Screen Log, Warnings
set name     = jana
set release  = `./get_coptions release`
set repo     = `./get_coptions repo`/jana
set version  = $JANA_VERSION
set filename =  jana"_"$JANA_VERSION".tgz"
set arch     = `./get_coptions arch`
set opt      = `./get_coptions copt`
set blog     = `./get_coptions logFile jana`
set blogS    = `./get_coptions logFileS jana`

# Write options on screen
./get_coptions log $name $version $filename $release $arch $opt

if($1 == "src"|| $1 == "make") goto $1

# Source Build
src:
	# start message
	$getCoptions installLog $name $version

	# creating build and source dirs
	$getCoptions removeAndCreate $JANA_HOME

	# unpacking inside source
	cd $JLAB_SOFTWARE/jana
	$getCoptions getAndUnpack $repo $filename
if($1 == "src") exit

# make
	make:

	# log start of compilation
	$getCoptions logStart $blog $blogS

	setenv BMS_OSNAME $OSRELEASE
	cd $JLAB_SOFTWARE/jana/jana_$JANA_VERSION

	scons $opt install >> $blog
	mv $BMS_OSNAME/* $JANA_HOME

	# log end of compilation, total time
	$getCoptions logEnd  $blog
	$getCoptions logTime $blog

if($1 == "make") exit

# Done
echo " > Done."
echo





# Clean ups
rm -rf $JANA_HOME/src
rm -rf $JLAB_SOFTWARE/jana/$filename
rm -rf $JLAB_SOFTWARE/jana/jana_$JANA_VERSION


# Done!
echo done
echo


