#!/bin/csh -f

# Get the jana tar file from the jana website:
# http://www.jlab.org/JANA/downloads.php
# zip if necessary, and copy to:
# ftp:/u/group/12gev_phys/www/packages/sources/jana

# Additional settings at the top of get_coptions
set getCoptions = $JLAB_ROOT/$JLAB_VERSION/install/get_coptions 

# Options, Screen Log, Warnings
set name     = jana
set release  = `$getCoptions release`
set repo     = `$getCoptions repo`/jana
set version  = $JANA_VERSION
set filename =  JANA"-"$JANA_VERSION".tar.gz"
set opt      = `$getCoptions copt`
set blog     = `$getCoptions logFile jana`
set blogS    = `$getCoptions logFileS jana`

# Write options on screen
$getCoptions log $name $version $filename $release $opt

if($1 == "src"|| $1 == "make") goto $1

# Source Build
src:
	# start message
	$getCoptions installLog $name $version

	# creating build and source dirs
	$getCoptions removeAndCreate $JANA_HOME

	# unpacking inside source
	cd $JLAB_SOFTWARE/jana
	$getCoptions getAndUnpack $repo $filename
if($1 == "src") exit

# make
	make:

	# log start of compilation
	$getCoptions logStart $blog $blogS

	setenv BMS_OSNAME $OSRELEASE
	cd $JLAB_SOFTWARE/jana/JANA-$JANA_VERSION

	scons $opt install >> $blog
	mv $BMS_OSNAME/* $JANA_HOME

	# log end of compilation, total time
	$getCoptions logEnd  $blog
	$getCoptions logTime $blog

if($1 == "make") exit

# Done
echo " > Done."
echo

# Clean ups
rm -rf $JANA_HOME/src
rm -rf $JLAB_SOFTWARE/jana/$filename
rm -rf $JLAB_SOFTWARE/jana/jana_$JANA_VERSION

# Done!
echo done
echo


