#!/bin/csh -f

# Additional settings at the top of get_coptions
source get_coptions env
set getCoptions = $JLAB_ROOT/$JLAB_VERSION/install/get_coptions 

# Options, Screen Log, Warnings
set name     = mlibrary
set release  = `$getCoptions release`
set repo     = `$getCoptions repo`/mlibrary
set version  = $MLIBRARY_VERSION
set filename =  mlibrary"_"$MLIBRARY_VERSION".tar.gz"
set opt      = `$getCoptions copt`
set blog     = `$getCoptions logFile mlibrary`
set blogS    = `$getCoptions logFileS mlibrary`

# Write options on screen
$getCoptions log $name $version $filename $release $opt

if($1 == "src"|| $1 == "make") goto $1

# Source Build
src:
	# start message
	$getCoptions installLog $name $version

	# creating build and source dirs
	$getCoptions removeAndCreate $JLAB_SOFTWARE/mlibrary/$MLIBRARY_VERSION

	# unpacking inside source
	cd $JLAB_SOFTWARE/mlibrary
	$getCoptions getAndUnpackTo $repo $filename $MLIBRARY_VERSION
if($1 == "src") exit

# make
make:

	cd $MLIBRARY

	# log start of compilation
	$getCoptions logStart $blog $blogS

	echo
	echo " > Compiling cadmesh..."
	echo
	./compileCmesh

	# Adding LIBRARY="shared" in case gemc is built as a library
	echo " > Compiling mlibrary..."
	echo
	scons $opt OPT=1 LIBRARY="shared" >>  $blog

	# log end of compilation, total time
	$getCoptions logEnd  $blog
	$getCoptions logTime $blog

if($1 == "make") exit

# Done
echo " > Done."
echo





