#!/bin/csh -f

# Additional settings at the top of get_coptions
set getCoptions = $JLAB_ROOT/$JLAB_VERSION/install/get_coptions

# Linking mysql distributions from OS release
# These need to be pre-installed
echo
echo " > Linking to local mysql distributions"

mkdir -p $JLAB_SOFTWARE/mysql

$getCoptions removeAndCreate $JLAB_SOFTWARE/mysql/include
$getCoptions removeAndCreate $JLAB_SOFTWARE/mysql/lib

# We copy the libraries and includes instead of making symlinks with ln -sfn
# The files are small and this solve the problem of a central installation and user mounting that installation from
# remote computer cause the link would point to their local /usr/lib

# Darwin: assuming brew installation
if(`uname` == "Darwin") then

	set brewInstallDir = "na"
	if ( -d /usr/local/Cellar ) then
		set brewInstallDir = /usr/local/Cellar
	else if ( -d  /opt/homebrew ) then
		set brewInstallDir =  /opt/homebrew
	endif


	set msqlver    = `ls -t $brewInstallDir/mysql | head -1`

	echo "   MYSQL version $msqlver"

	cp -r $brewInstallDir//mysql/$msqlver/include/mysql/* $JLAB_SOFTWARE/mysql/include/
	cp -r $brewInstallDir//mysql/$msqlver/lib/*           $JLAB_SOFTWARE/mysql/lib

# Linux
else if(`uname` == "Linux") then
	cp -r /usr/include/mysql/* $JLAB_SOFTWARE/mysql/include/

	# Linux - fedora line
	if( -f /etc/fedora-release || -f /etc/redhat-release) then
		cp /usr/lib64/mysql/* $JLAB_SOFTWARE/mysql/lib/
	# Linux - Ubuntu line
	else if( -f /etc/os-release) then
		cp /usr/lib/x86_64-linux-gnu/* $JLAB_SOFTWARE/mysql/lib/
	endif
endif

echo " > Done."
echo



