#!/bin/csh -f

# Additional settings at the top of get_coptions
source get_coptions env
set getCoptions = $JLAB_ROOT/$JLAB_VERSION/install/get_coptions 

# Options, Screen Log, Warnings
set name     = mlibrary
set release  = `./get_coptions release`
set repo     = `./get_coptions repo`/mlibrary
set version  = $MLIBRARY_VERSION
set filename =  mlibrary"_"$MLIBRARY_VERSION".tar.gz"
set arch     = `./get_coptions arch`
set opt      = `./get_coptions copt`
set blog     = `./get_coptions logFile mlibrary`
set blogS    = `./get_coptions logFileS mlibrary`

# Write options on screen
./get_coptions log $name $version $filename $release $arch $opt

if($1 == "src"|| $1 == "make") goto $1

# Source Build
src:
	# start message
	$getCoptions installLog $name $version

	# creating build and source dirs
	$getCoptions removeAndCreate $JLAB_SOFTWARE/mlibrary/$MLIBRARY_VERSION

	# unpacking inside source
	cd $JLAB_SOFTWARE/mlibrary
	$getCoptions getAndUnpackTo $repo $filename $MLIBRARY_VERSION
if($1 == "src") exit

# make
make:

	cd $MLIBRARY

	# log start of compilation
	$getCoptions logStart $blog $blogS

	echo
	echo " > Compiling cadmesh..."
	echo
	./compileCmesh

	# Adding LIBRARY="shared" in case gemc is built as a library
	echo " > Compiling mlibrary..."
	echo
	scons $opt LIBRARY="shared" >>  $blog


	# log end of compilation, total time
	$getCoptions logEnd  $blog
	$getCoptions logTime $blog

if($1 == "make") exit

# Done
echo " > Done."
echo





