#!/bin/csh -f

# Additional settings at the top of get_coptions
source get_coptions env

# Options, Screen Log, Warnings
set arch     = `./get_coptions arch`
set release  = `./get_coptions release`
set repo     = `./get_coptions repo`/qt

set system = ""
set filename = ""
if(`echo $release | grep mac   | wc | awk '{print $1}'` == "1") then
	set filename = "qt-opensource-mac-x64-"$QT_VERSION".dmg"
	set system = "Mac"
else if(`echo $release | grep Linux | wc | awk '{print $1}'` == "1") then
	if($arch == "32") then
		set filename = "qt-opensource-linux-x86-"$QT_VERSION".run"
	else
		set filename = "qt-opensource-linux-x64-"$QT_VERSION".run"
	endif
	set system = "Linux"
endif

# if option system is given, try to link to the system qt
if($1 == "system") then
	if($system == "Mac") then
		set majorQtVersion = `\ls -rt /usr/local/Cellar | grep qt`
		set minorQtVersion = `\ls -rt /usr/local/Cellar/$majorQtVersion | tail -1`
		set SQTDIR = /usr/local/Cellar/$majorQtVersion/$minorQtVersion
		echo
		echo System QT detected in $SQTDIR
		echo Linking to this qt installation.
		echo

		rm -rf   $QTDIR
		mkdir -p $QTDIR

		# linking the relevant stuff
		ln -sfn $SQTDIR/lib $QTDIR/lib
		ln -sfn $SQTDIR/include $QTDIR/include
		ln -sfn $SQTDIR/bin $QTDIR/bin
		ln -sfn $SQTDIR/mkspecs $QTDIR/mkspecs
		ln -sfn $SQTDIR/plugins $QTDIR/plugins

	# Using system QT for Linux.
	else if(`uname` == "Linux") then

	# Linux - fedora line
	if( -f /etc/fedora-release || -f /etc/redhat-release) then
		ln -sfn /usr/include $QTDIR/include

		if($arch == "32") then
			ln -sfn /usr/lib $QTDIR/lib
		else if($arch == "64") then
			ln -sfn /usr/lib64 $QTDIR/lib
		endif

	# Linux - Ubuntu line
	else if( -f /etc/os-release) then
		ln -sfn /usr/include/qt5 $QTDIR/include
		if($arch == "32") then
			ln -sfn /usr/lib/xi386-linux-gnu $QTDIR/lib
		else if($arch == "64") then
			ln -sfn /usr/lib/x86_64-linux-gnu $QTDIR/lib
		endif
	endif
else
	# Using offline Installer
	echo
	echo Installing QT using the offline installer.
	echo
	echo $system detected. Downloading $filename
	echo

	rm $filename
	wget $repo/$filename
	chmod u+x $filename

	echo Download Successfull. Please execute:
	echo
	if($system == "Mac") then
		echo open $filename
	else if($system == "Linux") then
		echo ./$filename
	endif
	echo
	echo Then follow the installation instructions. You can skip the creation of a qt account.
	echo
	echo \!\!\! WARNING WARNING WARNING \!\!\!
	echo
	echo The qt installation program will ask to verify the installation folder.
	echo Make sure to clear the default installation location and copy/parse this instead:
	echo
	echo $JLAB_SOFTWARE/qt/$QT_VERSION
	echo
	echo Make sure to include the Source Components during the installation process.
	echo
endif


