#!/bin/csh -f

# At JLab Robert Michaels is taking care of the ROOT installation
# chgrp -R 12gev_phys root
# chmod -R 775 root
#
# Everywhere else root is installed with brew or yum


#!/bin/csh -f



if($system == "Mac") then

	set rootVersion = `\ls -rt /usr/local/Cellar/root | tail -1`
	set SROOT = /usr/local/Cellar/root/rootVersion
	echo
	echo System ROOT, version $rootVersion
	echo Linking to $SROOT installation.
	echo

	rm -rf   $ROOTSYS
	mkdir -p $ROOTSYS

#	 linking the relevant stuff
	ln -sfn $SROOT/lib     $ROOTSYS/lib
	ln -sfn $SROOT/include $ROOTSYS/include
	ln -sfn $SROOT/bin     $ROOTSYS/bin
	ln -sfn $SROOT/etc     $ROOTSYS/etc
	ln -sfn $SROOT/share   $ROOTSYS/share

# Using system QT for Linux.
else if($system == "Linux") then

	# explicit path to qmake
	set minorQtVersion = `/usr/lib64/qt5/bin/qmake --version | grep Qt | awk '{print $4}'`

	echo
	echo System QT, system version $minorQtVersion will be used
	echo Linking to $minorQtVersion installation.
	echo

	rm -rf   $QTDIR
	mkdir -p $QTDIR

endif

echo Done!
echo
