#!/bin/csh -f

# Additional settings at the top of get_coptions
set getCoptions = $JLAB_ROOT/$JLAB_VERSION/install/get_coptions 

# Options
set name     = scons_bm
set release  = `$getCoptions release`
set repo     = `$getCoptions repo`/scons_bm
set version  = $SCONS_BM_VERSION
set filename =  scons_bm_$SCONS_BM_VERSION".tar.gz"


echo
echo " > Scons Build Model Version " $SCONS_BM_VERSION
echo

# Getting source file
echo " > Installing scons build model - version "$version". Getting package from repository..."
$getCoptions removeAndCreate $JLAB_ROOT/noarch/scons_bm/$SCONS_BM_VERSION

cd $SCONS_BM/..
$getCoptions getAndUnpackTo $repo $filename $SCONS_BM_VERSION

echo "Done."
echo

