#!/bin/zsh

# if the environment variables GEMC3_BASE_DIR and GEMC3_VERSION are not set, exit
if [[ -z "$GEMC3_BASE_DIR" || -z "$GEMC3_VERSION" ]]; then
	echo "$red > GEMC3_BASE_DIR and GEMC3_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

what="gemc3"
what_version="$GEMC3_VERSION"
base_dir="$GEMC3_BASE_DIR/$GEMC3_VERSION"
grepo="https://github.com/gemc/src/archive/refs/tags/$what_version.tar.gz"
tar_strip=1  # tarball number of subdirs to strip

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

log_general "$what" "$what_version" "$grepo" "$base_dir"

unpack_source_in_directory_from_url "$grepo" "$base_dir" "$tar_strip"

scons_build_and_install "$base_dir"

echo "$magenta > $what installation completed.$reset"
echo
