#!/bin/zsh

# if the environment variables CCDB_HOME and CCDB_VERSION are not set, exit
if [[ -z "$CCDB_HOME" || -z "$CCDB_VERSION" ]]; then
	echo "$red > CCDB_HOME and CCDB_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

filename="ccdb/ccdb-$CCDB_VERSION.tar.gz" # includes subdirectory name
tar_strip=1                               # in the tarball, the source is inside ccdb-version


base_dir=$CCDB_HOME

log_general ccdb "$CCDB_VERSION" "$filename" "$base_dir"

unpack_source_in_directory_from_jlab_repo "$filename" "$base_dir" "$tar_strip"

unset SCONSFLAGS
scons_build_and_install "$base_dir"

