#!/bin/zsh

# if the environment variables BANKS and BANKS_VERSION are not set, exit
if [[ -z "$BANKS" || -z "$BANKS_VERSION" ]]; then
	echo "$red > BANKS and BANKS_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

filename="banks/banks-$BANKS_VERSION.tar.gz" # includes subdirectory name
tar_strip=1                               # in the tarball, the source is inside version

# tar packages downloaded on the farm with:
# cd /group/12gev_phys/www/packages/sources/banks
# wget https://github.com/maureeungaro/banks/archive/refs/tags/v1.9.tar.gz -O banks-1.9.tar.gz


base_dir=$BANKS

log_general banks "$BANKS_VERSION" "$filename" "$base_dir"

unpack_source_in_directory "$filename" "$base_dir" "$tar_strip"

scons_build_and_install "$base_dir"

