#!/bin/zsh -i
# shell has to be interactive to load modules

. "$(dirname "$(readlink -f "$0")")"/functions.zsh

if [[ $# -eq 1 ]]; then
	geant4_version=$1
else
	# error
	echo " > ERROR: No geant4 version given. Exiting."
	exit 1
fi

echo " > Installing geant4 version $geant4_version"
echo

module purge
module load sim_system
module load geant4/$geant4_version
if [[ $? -ne 0 ]]; then
	echo " > ERROR: module load geant4/$geant4_version failed. Exiting."
	exit 1
fi
echo

echo " > Checking / Installing missing dependencies for geant4 version $geant4_version"
[ "$(moduleTestResult .clhep   $CLHEP_VERSION)"   -eq 0 ] && echo " > clhep $CLHEP_VERSION is installed"     || install_clhep
[ "$(moduleTestResult .xercesc $XERCESC_VERSION)" -eq 0 ] && echo " > xercesc $XERCESC_VERSION is installed" || install_xercesc

# copy qt if geant4 is not 11
if ! [[ $geant4_version == 11.* ]]; then
	[ "$(moduleTestResult .qt      $QT_VERSION)"      -eq 0 ] && echo " > qt $QT_VERSION is installed"           || copy_qt
fi

echo " > Done with dependencies, now checking / installing geant4 data"
if [ ! -d "$G4NEUTRONHPDATA" ] ||
	[ ! -d "$G4LEDATA" ] ||
	[ ! -d "$G4LEVELGAMMADATA" ] ||
	[ ! -d "$G4RADIOACTIVEDATA" ] ||
	[ ! -d "$G4PARTICLEXSDATA" ] ||
	[ ! -d "$G4PIIDATA" ] ||
	[ ! -d "$G4REALSURFACEDATA" ] ||
	[ ! -d "$G4SAIDXSDATA" ] ||
	[ ! -d "$G4ABLADATA" ] ||
	[ ! -d "$G4INCLDATA" ] ||
	[ ! -d "$G4ENSDFSTATEDATA" ]; then
	install_geant4_data
fi

echo " > Done with geant4 data, now fetching and compiling geant4 source code"
[ "$(moduleTestResult geant4 $G4_VERSION)" -eq 0 ] && echo " > Done with geant4 source" || install_geant4_source

cd $G4INSTALL
find ./ -type f -name "*.tgz" -exec rm -rf {} +
find ./ -type f -name "*.tar.gz" -exec rm -rf {} +

echo " > Now testing geant4 installation:"
module test geant4/$geant4_version
exit $?
