#!/bin/zsh

# if the environment variables BANKS and BANKS_VERSION are not set, exit
if [[ -z "$BANKS" || -z "$BANKS_VERSION" ]]; then
	echo "$red > BANKS or BANKS_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

what="banks"
what_version="$BANKS_VERSION"
base_dir="$BANKS"
grepo="https://github.com/maureeungaro/banks/archive/refs/tags/v$what_version.tar.gz"
tar_strip=1  # tarball number of subdirs to strip

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

log_general "$what" "$what_version" "$grepo" "$base_dir"

unpack_source_in_directory_from_url "$grepo" "$base_dir" "$tar_strip"

scons_build_and_install "$base_dir"

echo "$magenta > $what installation completed.$reset"
echo

