#!/bin/zsh

# if the environment variables SCIG and SCIG_VERSION are not set, exit
if [[ -z "$SCIG" || -z "$SCIG_VERSION" ]]; then
	echo "$red > SCIG and SCIG_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

filename="scig/scig-$SCIG_VERSION.tar.gz" # includes subdirectory name
tar_strip=1                               # in the tarball, the source is inside scons_bm

# tar packages downloaded on the farm with:
# cd /group/12gev_phys/www/packages/sources/scig
# wget https://github.com/gemc/sci-g/archive/refs/tags/1.0.tar.gz -O scig-1.0.tar.gz
# wget https://github.com/gemc/sci-g/archive/refs/tags/1.1.tar.gz -O scig-1.1.tar.gz

base_dir="$SCIG"

log_general scig "$SCIG_VERSION" "$filename" "$base_dir"

unpack_source_in_directory_from_jlab_repo "$filename" "$base_dir" "$tar_strip"

echo "$magenta > scig installation completed.$reset"
echo

