#!/bin/zsh

# if the environment variables EVIO and EVIO_VERSION are not set, exit
if [[ -z "$EVIO" || -z "$EVIO_VERSION" ]]; then
	echo "$red > EVIO or EVIO_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

what="evio"
what_version="$EVIO_VERSION"
base_dir="$SIM_HOME/$what"
srepo="https://github.com/JeffersonLab/evio_clas12"

source "$(dirname "$(readlink -f "$0")")"/functions.zsh
log_general "$what" "$what_version" "$srepo" "$base_dir"

mkdir -p $base_dir ; cd $base_dir
git  clone  --single-branch -b "$what_version" "$srepo" $what_version

cd $what_version || exit
scons  -j "$n_cpu" || exit

# cleaning up
rm -f .sconsign.dblite # for some reason this still linger
find ./ -name "*.o" -delete

echo "$magenta > $what installation completed.$reset"
echo

