#!/bin/zsh

# this legacy geant4 install script still uses data on the jlab repo

# if the environment variables G4DATA_DIR and G4_VERSION are not set, exit
if [[ -z "$G4DATA_DIR" || -z "$G4_VERSION" ]]; then
	echo "$red > G4DATA_DIR and G4_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

# tar packages downloaded on the farm with - look on tags > download icon
# cd /group/12gev_phys/www/packages/sources/geant4_data/version
# wget the links on the g4 page - and update the version numbers on .g4data


source "$(dirname "$(readlink -f "$0")")"/functions.zsh

DATAFILES=(
		G4NDL.$g4ndl_version.tar.gz
		G4EMLOW.$g4emlow_version.tar.gz
		G4PhotonEvaporation.$g4photonevaporation_version.tar.gz
		G4RadioactiveDecay.$g4radioactivedecay_version.tar.gz
		G4SAIDDATA.$g4saidata_version.tar.gz
		G4PARTICLEXS.$g4particlexs_version.tar.gz
		G4ABLA.$g4abla_version.tar.gz
		G4INCL.$g4incl_version.tar.gz
		G4PII.$g4pii_version.tar.gz
		G4ENSDFSTATE.$g4ensdfstate_version.tar.gz
		G4RealSurface.$g4real_surface_version.tar.gz
)

tar_strip=0

# loop over DATAFILES
for file in $DATAFILES; do
  unpack_source_in_directory_from_url https://cern.ch/geant4-data/datasets/$file $G4DATA_DIR $tar_strip 1
done