#!/bin/zsh

# if the environment variables EVIO and EVIO_VERSION are not set, exit
if [[ -z "$FIELD_DIR" ]]; then
	echo "$red > FIELD_DIR environment variables is not set. Exiting.$reset"
	exit 1
fi

mkdir -p $FIELD_DIR
base_dir="$FIELD_DIR"

# fieds used for data:
# https://github.com/JeffersonLab/clas12-offline-software/blob/development/etc/services/data.yaml
brepo="https://clasweb.jlab.org/clas12offline/magfield"
maps=(Symm_solenoid_r601_phi1_z1201_13June2018 Full_torus_r251_phi181_z251_25Jan2021 Full_torus_r251_phi181_z251_03March2020 Symm_torus_r2501_phi16_z251_24Apr2018)
for map in $maps; do
  field="$brepo/$map.dat"
	if [ ! -f "$base_dir/$map.dat" ]; then
		echo "$magenta > Downloading $field$reset"
		wget -q -P $base_dir $field
	fi
done

# ASCII files fields
brepo="https://clasweb.jlab.org/12gev/field_maps"
maps=(TorusSymmetric clas12NewSolenoidFieldMap)
for map in $maps; do
  field="$brepo/$map.dat"
	if [ ! -f "$base_dir/$map.dat" ]; then
		echo "$magenta > Downloading $field$reset"
		wget -q -P $base_dir $field
	fi
done

echo "$magenta > Fields installation completed.$reset"
echo

