#!/bin/zsh


base_dir="$FIELD_DIR"
brepo="https://clasweb.jlab.org/clas12offline/magfield/"

maps=(Symm_solenoid_r601_phi1_z1201_13June2018 Symm_torus_r2501_phi16_z251_24Apr2018 Symm_solenoid_r601_phi1_z1201_12May2019 Full_torus_r251_phi181_z251_03March2020)

for map in $maps; do
	if [ ! -f "$base_dir/$map" ]; then
		echo "$magenta > Downloading $map...$reset"
		wget -q -P $base_dir $brepo/$map
	fi
done

echo "$magenta > Fields installation completed.$reset"
echo

