#!/bin/zsh -i

# shell has to be interactive to load modules

# on fedora and ubuntu installation dir is different for modules
# at JLab we need to use modules 5.2 and higher
# also checking for container env setup in /app
[[ -f /usr/share/Modules/init/zsh ]] && . /usr/share/Modules/init/zsh
[[ -f /usr/share/modules/init/zsh ]] && . /usr/share/modules/init/zsh
[[ -f /apps/modules/5.2.0/init/zsh ]] && . /apps/modules/5.2.0/init/zsh
[[ -f /app/localSetup.sh ]] && . /app/localSetup.sh

. "$(dirname "$(readlink -f "$0")")"/functions.zsh

if [[ $# -eq 1 ]]; then
	sim_version=$1
else
	# error
	echo " > ERROR: No sim version given. Exiting."
	exit 1
fi

echo " > sim_version: $sim_version"
echo

echo " > Checking missing modules in sim version $sim_version"
module unload sim
module unload gemc
module unload gemc3
module load sim/$sim_version

# if the above command fails, exit
if [[ $? -ne 0 ]]; then
	echo " > ERROR: module load sim/$sim_version failed. Exiting."
	exit 1
fi
echo

[ "$(moduleTestResult .clhep $CLHEP_VERSION)" -eq 0 ] && echo " > clhep is installed" || install_clhep
[ "$(moduleTestResult .xercesc $XERCESC_VERSION)" -eq 0 ] && echo " > xercesc is installed" || install_xercesc
[ "$(moduleTestResult .qt $QT_VERSION)" -eq 0 ] && echo " > qt is installed" || copy_qt
[ "$(moduleTestResult .g4data $G4_VERSION)" -eq 0 ] && echo " > g4data is installed" || install_geant4_data
[ "$(moduleTestResult .geant4 $G4_VERSION)" -eq 0 ] && echo " > geant4 is installed" || install_geant4

# test for library existence
echo
echo SIM Tests:
echo
[ -f "$CLHEP_BASE_DIR/lib/libCLHEP.a" ] && echo CLHEP success || whine_and_quit "$CLHEP_BASE_DIR/lib/libCLHEP.a "
[ -f "$XERCESCROOT/bin/CreateDOMDocument" ] && echo XERCESC success || whine_and_quit "$XERCESCROOT/bin/CreateDOMDocument not found"
[ -d "$QTDIR/lib" ] && echo QT success || whine_and_quit "$QTDIR/lib not found"
[ -d "$G4LEDATA" ] && echo GEANT4 Data success || whine_and_quit "$G4LEDATA not found"
# not sure why when this is run for the first time, or in autobuild, the G4LIB is not set to lib64 but to lib
if [[ -d "$G4LIB" ]]; then
	echo "$G4LIB success"
else
	newG4LIB=$(echo $G4LIB | sed 's/lib/lib64/')
	[ -d "$newG4LIB" ] && echo "$newG4LIB success" || whine_and_quit "$newG4LIB or $G4LIB not found"
fi
echo
