#!/bin/zsh

# if the environment variables GEMC is not set, exit
if [[ -z "$GEMC"  ]]; then
	echo "$red > $GEMC is not set. Exiting.$reset"
	exit 1
fi

what="gemc"
what_version="$GEMC_VERSION"
base_dir="$GEMC_BASE_DIR/$GEMC_VERSION"
grepo="https://github.com/gemc/source/archive/refs/tags/v$what_version.tar.gz"
tar_strip=1  # tarball number of subdirs to strip

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

log_general "$what" "$what_version" "$grepo" "$base_dir"

unpack_source_in_directory_from_url "$grepo" "$base_dir" "$tar_strip"

scons_build_and_install "$base_dir"

cd $GEMC
git clone https://github.com/gemc/api

echo "$magenta > $what installation completed.$reset"
echo
