#!/bin/zsh



magenta=`tput setaf 5`
reset=`tput sgr0`

source "$(dirname "$(readlink -f "$0")")"/functions.zsh


# QT 6 Installation
###################


# increase opened files limit
ulimit -S -n 2048


make -j "$n_cpu"



# QT 6 Installation
###################

# git submodule init qtrepotools qtbase qtimageformats qtshadertools qtsvg
# qtlanguageserver qtdeclarative qtactiveqt qttools qttranslations qtquicktimeline
# qtquick3d qtmultimedia qtwebsockets qtwebchannel qtserialport
# qtpositioning qtwebengine qtdoc qtqa



QT_VERSION=6.8

source_dir=qt6
install_dir=/Users/ungaro/tmp/qt6-install

git clone git://code.qt.io/qt/qt5.git $source_dir
cd $source_dir || exit
git checkout $QT_VERSION

 ./init-repository --module-subset=qtbase
cd ..

# 2/18/25: giving up on this as qt installation does not provide pkg-config files
# perhaps I can try with the cmake files.
mkdir qt6-build
cd qt6-build
../qt6/configure -prefix $install_dir -release -static -DQT_BUILD_TESTS_BY_DEFAULT=OFF -DQT_BUILD_EXAMPLES=OFF -DQT_BUILD_EXAMPLES_BY_DEFAULT=OFF -DFEATURE_pcre2=system -pkg-config
../qt6/configure -prefix $install_dir -release -DQT_BUILD_TESTS_BY_DEFAULT=OFF -DQT_BUILD_EXAMPLES=OFF -DQT_BUILD_EXAMPLES_BY_DEFAULT=OFF -DFEATURE_pcre2=system

cmake --build .
cmake --install .


