#!/bin/zsh

# if the environment variables GLIBRARY and GLIBRARY_VERSION are not set, exit
if [[ -z "$GLIBRARY" || -z "$GLIBRARY_VERSION" ]]; then
	echo "$red > GLIBRARY and GLIBRARY_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

what="glibrary"
what_version="$GLIBRARY_VERSION"
base_dir="$GLIBRARY"
grepo="https://github.com/gemc/glibrary/archive/refs/tags/$what_version.tar.gz"
tar_strip=1  # tarball number of subdirs to strip

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

log_general "$what" "$what_version" "$grepo" "$base_dir"

unpack_source_in_directory_from_url "$grepo" "$base_dir" "$tar_strip"

scons_build_and_install "$base_dir"

echo "$magenta > $what installation completed.$reset"
echo

# notice that if the system is updated, the OPENGL library may point to a different location
# for example /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/OpenGL.framework
# instead of 13.0

