#!/bin/zsh

# if the environment variables GEMC3_BASE_DIR and GEMC3_VERSION are not set, exit
if [[ -z "$GEMC" || -z "$GEMC3_VERSION" ]]; then
	echo "$red > GEMC3_BASE_DIR or GEMC3_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

what="gemc3"
what_version="$GEMC3_VERSION"
install_dir="$GEMC"
source_dir="gemc3_source"
grepo="https://github.com/gemc/src"

source "$(dirname "$(readlink -f "$0")")"/functions.zsh
rm -rf $source_dir
clone_tag "$grepo" "$what_version" "$source_dir"
cd $source_dir

dir_remove_and_create   "$install_dir"
meson_install "--native-file=release.ini" "$install_dir"
cd ..
rm -rf $source_dir

echo "$magenta > $what installation completed.$reset"
echo
