#!/bin/zsh

# if the environment variables XERCESCROOT and XERCESC_VERSION are not set, exit
if [[ -z "$XERCESCROOT" || -z "$XERCESC_VERSION" ]]; then
	echo "$red > XERCESCROOT and XERCESC_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

filename="xercesc/xerces-c-$XERCESC_VERSION.tar.gz" # includes subdirectory name
tar_strip=1                                         # in the tarball, the source is inside xerces-c-VERSION

source_dir=$XERCESCROOT/source
build_dir=$XERCESCROOT/build
base_dir=$XERCESCROOT
cmake_options="-Wno-dev"


log_general xercesc "$XERCESC_VERSION" "$filename" "$base_dir"

unpack_source_in_directory_from_jlab_repo "$filename" "$source_dir" "$tar_strip"

cmake_build_and_install "$source_dir" "$build_dir" "$base_dir" "$cmake_options"

