#!/bin/zsh

# if the environment variables SCONS_BM and SCONS_BM_VERSION are not set, exit
if [[ -z "$SCONS_BM" || -z "$SCONS_BM_VERSION" ]]; then
	echo "$red > SCONS_BM and SCONS_BM_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

what="scons_bm"
what_version="$SCONS_BM_VERSION"
base_dir="$SCONS_BM"
grepo="https://github.com/maureeungaro/scons_bm/archive/refs/tags/$what_version.tar.gz"
tar_strip=1  # tarball number of subdirs to strip

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

log_general scons_bm "$SCONS_BM_VERSION" "$filename" "$base_dir"

unpack_source_in_directory_from_url "$filename" "$base_dir" "$tar_strip"

echo "$magenta > scons_bm installation completed.$reset"
echo

