#!/bin/zsh -i

# on fedora and ubuntu installation dir is different for modules
[[ -f /usr/share/Modules/init/sh ]] && source /usr/share/Modules/init/sh
[[ -f /usr/share/modules/init/sh ]] && source /usr/share/modules/init/sh

. "$(dirname "$(readlink -f "$0")")"/functions.zsh

if [[ $# -eq 1 ]]; then
	sim_version=$1
else
	# error
	echo " > ERROR: No sim version given. Exiting."
	exit 1
fi


echo " > sim_version: $sim_version"
echo


echo " > Checking missing modules in sim version $sim_version"
module unload sim
module unload gemc
module unload gemc3
module load	  sim/$sim_version

# if the above command fails, exit
if [[ $? -ne 0 ]]; then
	echo " > ERROR: module load sim/$sim_version failed. Exiting."
	exit 1
fi
echo

[ "$(moduleTestResult .clhep     $CLHEP_VERSION )"    -eq 0 ] && echo " > clhep is installed"    || install_clhep
[ "$(moduleTestResult .xercesc   $XERCESC_VERSION )"  -eq 0 ] && echo " > xercesc is installed"  || install_xercesc
[ "$(moduleTestResult .qt        $QT_VERSION)"        -eq 0 ] && echo " > qt is installed"       || copy_qt
[ "$(moduleTestResult .g4data    $G4_VERSION)"        -eq 0 ] && echo " > g4data is installed"   || install_geant4_data
[ "$(moduleTestResult .geant4    $G4_VERSION)"        -eq 0 ] && echo " > geant4 is installed"   || install_geant4






echo
module test sim/$sim_version

echo

