#!/bin/zsh

# if the environment variables SCIG and SCIG_VERSION are not set, exit
if [[ -z "$SCIG" || -z "$SCIG_VERSION" ]]; then
	echo "$red > SCIG and SCIG_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

what="scig"
what_version="$SCIG_VERSION"
base_dir="$SCIG"
grepo="https://github.com/gemc/sci-g/archive/refs/tags/$what_version.tar.gz"
srepo="https://github.com/maureeungaro/sci-g"
tar_strip=1  # tarball number of subdirs to strip

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

if [[ $what_version != "dev" ]]; then
  log_general "$what" "$what_version" "$grepo" "$base_dir"
  unpack_source_in_directory_from_url "$grepo" "$base_dir" "$tar_strip"
else
  log_general "$what" "$what_version" "$srepo" "$base_dir"
  echo "$magenta > cloning $srepo.$reset"
  mkdir "$SCIG"
  cd "$SCIG/.."
  rm -rf "dev"
  git clone "$srepo" "dev"
fi



echo "$magenta > $what installation completed.$reset"
echo

