#!/bin/zsh

# if the environment variables CLAS12TAG_BASE_DIR and CLAS12TAG_VERSION are not set, exit
if [[ -z "$CLAS12TAG_BASE_DIR" || -z "$CLAS12TAG_VERSION" ]]; then
	echo "$red > CLAS12TAG_BASE_DIR and CLAS12TAG_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

what="clas12Tags"
what_version="$CLAS12TAG_VERSION"
base_dir="$CLAS12TAG_BASE_DIR/$CLAS12TAG_VERSION"
grepo="https://github.com/gemc/clas12Tags/archive/refs/tags/$what_version.tar.gz"
tar_strip=1  # tarball number of subdirs to strip

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

log_general "$what" "$what_version" "$grepo" "$base_dir"

unpack_source_in_directory_from_url "$grepo" "$base_dir" "$tar_strip"

scons_build_and_install "$base_dir/source"

echo "$magenta > $what installation completed.$reset"
echo
