#!/bin/zsh

# if the environment variables SCIG and SCIG_VERSION are not set, exit
if [[ -z "$CLAS12_SYSTEMS" || -z "$CLAS12_SYSTEMS_VERSION" ]]; then
	echo "$red > $CLAS12_SYSTEMS and CLAS12_SYSTEMS_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

what="clas12_systems"
what_version="$CLAS12_SYSTEMS_VERSION"
base_dir="$CLAS12_SYSTEMS"
#grepo="https://github.com/maureeungaro/clas12-systems/archive/refs/tags/$CLAS12_SYSTEMS_VERSION.tar.gz"
grepo="https://github.com/gemc/clas12-systems/archive/refs/tags/$CLAS12_SYSTEMS_VERSION.tar.gz"
tar_strip=1  # tarball number of subdirs to strip

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

log_general "$what" "$what_version" "$grepo" "$base_dir"

unpack_source_in_directory_from_url "$grepo" "$base_dir" "$tar_strip"



echo "$magenta > $what installation completed.$reset"
echo

