#!/bin/zsh

# if the environment variables CLHEP_BASE_DIR and CLHEP_VERSION are not set, exit
if [[ -z "$CLHEP_BASE_DIR" || -z "$CLHEP_VERSION" ]]; then
	echo "$red > CLHEP_BASE_DIR and CLHEP_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

# tar packages downloaded on the farm with - look on tags > download icon
# cd /group/12gev_phys/www/packages/sources/clhep
# wget https://gitlab.cern.ch/CLHEP/CLHEP/-/archive/CLHEP_2_4_6_2/CLHEP-CLHEP_2_4_6_2.tar.gz -O clhep-2.4.6.2.tgz

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

filename="clhep/clhep-$CLHEP_VERSION.tgz" # includes subdirectory name
tar_strip=2                               # in the tarball, the source is inside VERSION/CLHEP

source_dir=$CLHEP_BASE_DIR/../source
build_dir=$CLHEP_BASE_DIR/../build
base_dir=$CLHEP_BASE_DIR
cmake_options="-Wno-dev"


log_general clhep "$CLHEP_VERSION" "$filename" "$base_dir"

unpack_source_in_directory_from_jlab_repo "$filename" "$source_dir" "$tar_strip"

cmake_build_and_install "$source_dir" "$build_dir" "$base_dir" "$cmake_options"

