#!/bin/zsh

# if the environment variables CLAS12TAG_BASE_DIR and CLAS12TAG_VERSION are not set, exit
if [[ -z "$CLAS12TAG_BASE_DIR" || -z "$CLAS12TAG_VERSION" ]]; then
	echo "$red > CLAS12TAG_BASE_DIR and CLAS12TAG_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

filename="clas12Tags/clas12Tags-$CLAS12TAG_VERSION.tar.gz" # includes subdirectory name
tar_strip=1                                             # in the tarball, the source is inside version

# tar packages downloaded on the farm with:
# cd /group/12gev_phys/www/packages/sources/clas12Tags
# wget https://github.com/gemc/clas12_tags/archive/refs/tags/4.4.2.tar.gz -O clas12Tags-4.4.2.tar.gz
# wget https://github.com/gemc/clas12_tags/archive/refs/tags/5.1.tar.gz   -O clas12Tags-5.1.tar.gz

base_dir=$CLAS12TAG_BASE_DIR/$CLAS12TAG_VERSION

log_general clas12Tags "$CLAS12TAG_VERSION" "$filename" "$base_dir"

unpack_source_in_directory "$filename" "$base_dir" "$tar_strip"

scons_build_and_install "$base_dir/source"

