#!/bin/zsh

# if the environment variables C12BFIELDS and CMAG_VERSION are not set, exit
if [[ -z "$CLAS12_CMAG" || -z "$CMAG_VERSION" ]]; then
	echo "$red > CLAS12_CMAG or CMAG_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

what="clas12_cmag"
what_version="$CMAG_VERSION"
base_dir="$SIM_HOME/$what"
grepo="https://github.com/JeffersonLab/clas12-cmag"

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

log_general "$what" "$what_version" "$grepo" "$base_dir"

mkdir -p $base_dir ; cd $base_dir
echo hello $(pwd)
git clone --recurse-submodules --single-branch -b v$what_version "$grepo" $what_version

cd $what_version/src || exit
make -j "$n_cpu" || exit

echo "$magenta > $what installation completed.$reset"
echo

