#!/bin/zsh

# if the environment variables C12BFIELDS and CMAG_VERSION are not set, exit
if [[ -z "$C12BFIELDS" || -z "$CMAG_VERSION" ]]; then
	echo "$red > C12BFIELDS and CMAG_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi


source "$(dirname "$(readlink -f "$0")")"/functions.zsh

filename="cmag/cmag-$CMAG_VERSION.tar.gz" # includes subdirectory name
tar_strip=1                               # in the tarball, the source is inside version


base_dir=$C12BFIELDS

log_general hipo "$CMAG_VERSION" "$filename" "$base_dir"

unpack_source_in_directory_from_jlab_repo "$filename" "$base_dir" "$tar_strip"

cd $C12BFIELDS/src
make -j "$n_cpu"
