#!/bin/zsh

# if the environment variables G4INSTALL and G4_VERSION are not set, exit
if [[ -z "$G4INSTALL" || -z "$G4_VERSION" ]]; then
	echo "$red > G4INSTALL or $G4_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

source_dir=$G4INSTALL/source
build_dir=$G4INSTALL/build
base_dir=$G4INSTALL
filename="https://gitlab.cern.ch/geant4/geant4/-/archive/v$G4_VERSION/geant4-v$G4_VERSION.tar.gz"
tar_strip=1 # in the tarball, the source is inside VERSION/CLHEP

# Full list of options and explanation:
# https://geant4-userdoc.web.cern.ch/UsersGuides/InstallationGuide/html/index.html

# assuming qmake is installed and in the path
qmake_path=$(which qmake)
cmake_gdml="  -DGEANT4_USE_GDML=ON -DXERCESC_ROOT_DIR=$XERCESCROOT"
cmake_clhep=" -DCLHEP_ROOT_DIR=$CLHEP_BASE_DIR"
cmake_qt5="   -DQT_QMAKE_EXECUTABLE=$qmake_path             -DGEANT4_USE_QT=ON"
cmake_qt6="   -DQT_QMAKE_EXECUTABLE=$qmake_path  -DGEANT4_USE_QT=ON -DGEANT4_USE_QT_QT6=ON"
cmake_data="  -DCMAKE_INSTALL_DATAROOTDIR=$G4INSTALL/data -DGEANT4_INSTALL_DATA=OFF -DGEANT4_INSTALL_PACKAGE_CACHE=ON"
cmake_pack="  -DBUILD_STATIC_LIBS=ON -DGEANT4_USE_SYSTEM_EXPAT=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DGEANT4_USE_SYSTEM_ZLIB=ON"
cmake_mt="    -DGEANT4_BUILD_MULTITHREADED=ON  -DGEANT4_BUILD_BUILTIN_BACKTRACE=OFF "
x11_option=" -DGEANT4_USE_OPENGL_X11=ON -DGEANT4_USE_RAYTRACER_X11=ON "

#  not used
# -DCMAKE_CXX_STANDARD=20
# -DGEANT4_USE_SYSTEM_ZLIB=ON
# -DBUILD_SHARED_LIBS=OFF
# -DDGEANT4_USE_USOLIDS=ON, requires vecgeom installed
# -DGEANT4_INSTALL_PACKAGE_CACHE=OFF
# -DBUILD_SHARED_LIBS=OFF

# add cmake_mt if G4_VERSION is 11.0 or higher
if [[ $G4_VERSION == 11.* ]]; then
	cmake_options="$cmake_gdml $cmake_clhep $cmake_qt6 $cmake_data $cmake_pack $cmake_mt $x11_option"
else
	cmake_options="$cmake_gdml $cmake_clhep $cmake_qt5 $cmake_data $cmake_pack $x11_option"
fi

case $(uname -s) in
Linux)
	;;
Darwin)
	;;
*)
	echo "Unsupported OS: $(uname -s)"
	exit 1
	;;
esac

source "$(dirname "$(readlink -f "$0")")"/functions.zsh
log_general geant4 "$G4_VERSION" "$filename" "$base_dir"

unpack_source_in_directory_from_url "$filename" "$source_dir" "$tar_strip"


# change fsqrt definition if geant4 version < 10.7
# fix m_barnch for geant4 10.7.4
if [[ $G4_VERSION == "10.6.2" ]]; then
	echo
	echo " > Geant4 version is $G4_VERSION, applying fsqrt patch to $source_dir/source/persistency/ascii/src/G4tgrEvaluator.cc"
	echo
	case $(uname -s) in
	Linux)
		sed -i s/fsqrt/fltsqrt/ "$source_dir/source/persistency/ascii/src/G4tgrEvaluator.cc"
		;;
	Darwin)
		/usr/bin/sed -i '' s/fsqrt/fltsqrt/ "$source_dir/source/persistency/ascii/src/G4tgrEvaluator.cc"
		;;
	*)
		echo "Unsupported OS: $(uname -s)"
		exit 1
		;;
	esac
elif [[ $G4_VERSION == "10.7.4" ]]; then
	echo
	echo " > Geant4 version is $G4_VERSION, applying m_barnch patch to $source_dir/source/analysis/g4tools/include/tools/wroot/columns.icc"
	echo
	case $(uname -s) in
	Linux)
		sed -i s/m_barnch/m_branch/ "$source_dir/source/analysis/g4tools/include/tools/wroot/columns.icc"
		;;
	Darwin)
		/usr/bin/sed -i '' s/m_barnch/m_branch/ "$source_dir/source/analysis/g4tools/include/tools/wroot/columns.icc"
		;;
	*)
		echo "Unsupported OS: $(uname -s)"
		exit 1
		;;
	esac
fi

cmake_build_and_install "$source_dir" "$build_dir" "$base_dir" "$cmake_options"
