#!/bin/zsh

# if the environment variables SCONS_BM and SCONS_BM_VERSION are not set, exit
if [[ -z "$SCONS_BM" || -z "$SCONS_BM_VERSION" ]]; then
	echo "$red > SCONS_BM or SCONS_BM_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

what="scons_bm"
what_version="$SCONS_BM_VERSION"
base_dir="$SCONS_BM"
grepo="https://github.com/maureeungaro/scons_bm/archive/refs/tags/v$what_version.tar.gz"
srepo="https://github.com/maureeungaro/scons_bm"
tar_strip=1  # tarball number of subdirs to strip

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

if [[ $what_version != "dev" ]]; then
  log_general "$what" "$what_version" "$grepo" "$base_dir"
  unpack_source_in_directory_from_url "$grepo" "$base_dir" "$tar_strip"
else
  echo make a link to the scons_bm dir containing the repo
fi



echo "$magenta > $what installation completed.$reset"
echo

