#!/bin/zsh

# if the environment variables DRIFTCHAMBERS and DRIFTCHAMBERS_VERSION are not set, exit
if [[ -z "$DRIFTCHAMBERS" || -z "$DRIFTCHAMBERS_VERSION" ]]; then
  echo "$red > DRIFTCHAMBERS ($DRIFTCHAMBERS) or DRIFTCHAMBERS_VERSION ($DRIFTCHAMBERS_VERSION) environment variables are not set. Exiting.$reset"
  exit 1
fi

what="driftchambers"
what_version="$DRIFTCHAMBERS_VERSION"
base_dir="$DRIFTCHAMBERS"
grepo="https://github.com/gavalian/driftchambers"

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

log_general "$what" "$what_version" "$grepo" "$base_dir"

# git cloning the tag because lz4 is not in the tarball
mkdir -p "$base_dir"
cd "$base_dir/".. || exit
rm -rf "$base_dir"
git clone --recurse-submodules --single-branch -b $what_version "$grepo" "$what_version"

cd "$DRIFTCHAMBERS" || exit
export HIPO_DIR=$HIPO
make 2>"dc_build_err.txt" 1>"dc_build_log.txt" || exit
# parallel installation does not work yet
#  make -j "$n_cpu" 2>"dc_build_err.txt" 1>"dc_build_log.txt" || exit


echo "$magenta > $what installation completed.$reset"
echo
