#!/bin/zsh

# if the environment variables MLIBRARY and MLIBRARY_VERSION are not set, exit
if [[ -z "$MLIBRARY" || -z "$MLIBRARY_VERSION" ]]; then
	echo "$red > MLIBRARY and MLIBRARY_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

what="mlibrary"
what_version="$MLIBRARY_VERSION"
base_dir="$MLIBRARY"
grepo="https://github.com/gemc/mlibrary/archive/refs/tags/v$what_version.tar.gz"
tar_strip=1  # tarball number of subdirs to strip

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

log_general "$what" "$what_version" "$grepo" "$base_dir"

unpack_source_in_directory_from_url "$grepo" "$base_dir" "$tar_strip"

cd $base_dir
./compileCmesh 2>"cmesh_build_err.txt" 1>"cmesh_build_log.txt" || exit

scons_build_and_install "$base_dir" "LIBRARY=shared"
