#!/bin/zsh

# if the environment variables HIPO and HIPO_VERSION are not set, exit
if [[ -z "$HIPO" || -z "$HIPO_VERSION" ]]; then
	echo "$red > HIPO and HIPO_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

source "$(dirname "$(readlink -f "$0")")"/functions.zsh

filename="hipo/hipo-$HIPO_VERSION.tar.gz" # includes subdirectory name
tar_strip=1                               # in the tarball, the source is inside version


base_dir=$HIPO

log_general hipo "$HIPO_VERSION" "$filename" "$base_dir"

unpack_source_in_directory_from_jlab_repo "$filename" "$base_dir" "$tar_strip"

# the tar file must contain the lz4 submodule. Done with:
# git clone --recurse-submodules https://github.com/gavalian/hipo.git
# gtar cvf hipo-1.8.tar --exclude=.git  hipo ;  gzip hipo-1.8.tar

cd $HIPO
mkdir -p lib
cd lz4
make -j "$n_cpu" 2>"lz4_build_err.txt" 1>"lz4_build_log.txt" || exit
cp lib/liblz4.* ../lib
cd ../hipo4
make -j "$n_cpu"




