#!/bin/tcsh -f

# will make symbolic links to the base installation
# will replace versions of versions.env
# will delete the new package(s) directory so the script can install them new

# The enviroment is already defined and the directory already created.

set baseRelease  = 1.3
set patchRelease = 1.3.1
set packages = (gemc)

echo
echo Linking the various $baseRelease packages...

foreach dontdo ($packages)
	foreach p (clhep xercesc qt geant4 mysql ccdb evio gemc root banks jana)
		if($p != $dontdo) then
			echo "  linking $p package"
			ln -s $JLAB_ROOT/$baseRelease/$OSRELEASE/$p $OSRELEASE/$p
		endif
	end
	echo
	echo "  linking scons_bm"
	ln -s $JLAB_ROOT/$baseRelease/scons_bm .
end

echo done.
cd install
foreach do ($packages)
	echo Now installing $do"..."
	./go_$do
end
echo done!
echo
echo


