#!/bin/tcsh -f

# will make symbolic links to the base installation
# will replace versions of versions.env
# will delete the new package(s) directory so the script can install them new

# The enviroment is already defined and the directory already created.

set baseRelease  = 1.3
set patchRelease = 1.3.1
set packages = (gemc)

echo
echo Creating distribution directory...
cd $JLAB_ROOT/$patchRelease
mkdir $OSRELEASE
echo done. Now linking the various $baseRelease packages...

foreach dontdo $(packages)
	foreach p (clhep xercesc qt geant4 scons_bm mysql ccdb gemc root banks jana)
		if($p != $dontdo) then
			echo Linking $p package
			ln -s ../$baseRelease/$OSRELEASE/$p $OSRELEASE/$p
		endif
	end
end

echo done!
echo
echo


