#!/bin/tcsh -f

# First argument is package name
# Second argument is version

if($#argv != 2 && $1 != doc) then
	echo " "
	echo "Usage:   "
	echo  "  >> go_tar package version"
	echo " "
	exit 0
endif


set pname   = $1
set pver    = $2
set remoted = "ftp.jlab.org:/u/group/12gev_phys/www/packages/sources"
set locald  = /opt/projects

echo
echo " Package: " $pname ", version: " $pver
echo


# common environment
if($pname == "ceInstall") then
	cd $locald/ceInstall
	rm -f ceInstall_$pver.*
	tar cvf ceInstall_$pver.tar  --exclude='go_tar' --exclude="doc" --exclude=".DS_Store" --exclude="releases.key" $pver
	gzip ceInstall_$pver.tar
	scp ceInstall_$pver.tar.gz $remoted/ceInstall
	scp $pver/install/install.html $remoted/ceInstall/$pver"_install.html"
	exit
endif


# scons scripts
if($pname == "bm") then
	cd $locald/scons_bm/
	rm -rf scons_bm-$pver.*
	tar cvf scons_bm-$pver.tar $pver/*
	gzip scons_bm-$pver.tar
	scp scons_bm-$pver.tar.gz $remoted/scons_bm
	exit
endif


# evio
if($pname == "evio") then
	cd $locald/evio/releases/$pver
	scons -c ; rm -rf lib bin
	cd ..
	rm -rf evio-$pver.*
	tar cvf evio-$pver.tar $pver/*
	gzip evio-$pver.tar
	scp evio-$pver.tar.gz $remoted/evio
	exit
endif


# gemc
# copying API in gemc
if($pname == "gemc") then
	if($pver == "devel") then
		cd $GEMC
		scons -c
		cd $locald/gemc/releases/
		rm -rf devel ; cp -r ../source devel
	endif
	cd $locald/gemc/releases/$pver
	scons -c ;
	cp -r $locald/gemc/api .
	cd $locald/gemc/releases
	rm -rf gemc-$pver.*
	tar cvf gemc-$pver.tar  --exclude=".DS_Store"  --exclude=".gitignore" --exclude=".sconsign.dblite" --exclude=".git" --exclude=".entitlements" --exclude="lib" $pver
	gzip gemc-$pver.tar
	scp gemc-$pver.tar.gz $remoted/gemc
	rm -rf $locald/gemc/releases/$pver/api
	exit
endif

# banks
if($pname == "banks") then
	cd $locald/banks/$pver
	setenv BANKS `pwd`
	scons -c ;
	cd ../
	rm -rf banks-$pver.*
	tar cvf banks-$pver.tar --exclude="banks.xcodeproj" --exclude="lib" $pver/*
	gzip banks-$pver.tar
	scp banks-$pver.tar.gz $remoted/banks
	exit
endif


# mlibrary
if($pname == "mlibrary") then
	if($pver == "devel") then
		cd $locald/mlibrary/
		scons -c
		cd $locald/mlibrary/releases/
		rm -rf devel ; mkdir devel ;
		foreach mlib (gruns options splash textProgressBar translationTable)
	      cp -r ../$mlib devel/
		end
		cp ../SConstruct devel
		# cadmesh needs download from the web directly
		# or it will pick cmake stuff if there - why people using cmake?
		cd devel
		git clone https://github.com/christopherpoole/CADMesh.git
		mv CADMesh cadmesh
	endif

	# echo remember to include a cadmesh release version on mlibrary
	cd $locald/mlibrary/releases/$pver
	scons -c ;
	cd ../
	rm -rf mlibrary-$pver.*
	tar cvf mlibrary-$pver.tar --exclude=".DS_Store"  --exclude=".gitignore" --exclude=".sconsign.dblite" --exclude=".git" --exclude=".entitlements" $pver/*
	gzip mlibrary-$pver.tar
	scp mlibrary-$pver.tar.gz $remoted/mlibrary
	exit
endif




echo
echo


